// Code generated by ent, DO NOT EDIT.

package imagestudiotemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imagestudiotemplate type in the database.
	Label = "image_studio_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldOriginalImageURL holds the string denoting the original_image_url field in the database.
	FieldOriginalImageURL = "original_image_url"
	// FieldImageHash holds the string denoting the image_hash field in the database.
	FieldImageHash = "image_hash"
	// FieldImageDownloadError holds the string denoting the image_download_error field in the database.
	FieldImageDownloadError = "image_download_error"
	// FieldPromptHash holds the string denoting the prompt_hash field in the database.
	FieldPromptHash = "prompt_hash"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldSourceName holds the string denoting the source_name field in the database.
	FieldSourceName = "source_name"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldLicense holds the string denoting the license field in the database.
	FieldLicense = "license"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldRequiresReference holds the string denoting the requires_reference field in the database.
	FieldRequiresReference = "requires_reference"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// Table holds the table name of the imagestudiotemplate in the database.
	Table = "image_studio_templates"
)

// Columns holds all SQL columns for imagestudiotemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKey,
	FieldMode,
	FieldTitle,
	FieldModel,
	FieldImage,
	FieldOriginalImageURL,
	FieldImageHash,
	FieldImageDownloadError,
	FieldPromptHash,
	FieldPrompt,
	FieldSourceName,
	FieldSourceURL,
	FieldSourceType,
	FieldLicense,
	FieldAuthor,
	FieldMeta,
	FieldTags,
	FieldRequiresReference,
	FieldEnabled,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// ImageValidator is a validator for the "image" field. It is called by the builders before save.
	ImageValidator func(string) error
	// DefaultOriginalImageURL holds the default value on creation for the "original_image_url" field.
	DefaultOriginalImageURL string
	// OriginalImageURLValidator is a validator for the "original_image_url" field. It is called by the builders before save.
	OriginalImageURLValidator func(string) error
	// DefaultImageHash holds the default value on creation for the "image_hash" field.
	DefaultImageHash string
	// ImageHashValidator is a validator for the "image_hash" field. It is called by the builders before save.
	ImageHashValidator func(string) error
	// DefaultImageDownloadError holds the default value on creation for the "image_download_error" field.
	DefaultImageDownloadError string
	// ImageDownloadErrorValidator is a validator for the "image_download_error" field. It is called by the builders before save.
	ImageDownloadErrorValidator func(string) error
	// DefaultPromptHash holds the default value on creation for the "prompt_hash" field.
	DefaultPromptHash string
	// PromptHashValidator is a validator for the "prompt_hash" field. It is called by the builders before save.
	PromptHashValidator func(string) error
	// PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	PromptValidator func(string) error
	// DefaultSourceName holds the default value on creation for the "source_name" field.
	DefaultSourceName string
	// SourceNameValidator is a validator for the "source_name" field. It is called by the builders before save.
	SourceNameValidator func(string) error
	// DefaultSourceURL holds the default value on creation for the "source_url" field.
	DefaultSourceURL string
	// SourceURLValidator is a validator for the "source_url" field. It is called by the builders before save.
	SourceURLValidator func(string) error
	// DefaultSourceType holds the default value on creation for the "source_type" field.
	DefaultSourceType string
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultLicense holds the default value on creation for the "license" field.
	DefaultLicense string
	// LicenseValidator is a validator for the "license" field. It is called by the builders before save.
	LicenseValidator func(string) error
	// DefaultAuthor holds the default value on creation for the "author" field.
	DefaultAuthor string
	// AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	AuthorValidator func(string) error
	// DefaultMeta holds the default value on creation for the "meta" field.
	DefaultMeta string
	// MetaValidator is a validator for the "meta" field. It is called by the builders before save.
	MetaValidator func(string) error
	// DefaultRequiresReference holds the default value on creation for the "requires_reference" field.
	DefaultRequiresReference bool
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the ImageStudioTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByOriginalImageURL orders the results by the original_image_url field.
func ByOriginalImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalImageURL, opts...).ToFunc()
}

// ByImageHash orders the results by the image_hash field.
func ByImageHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageHash, opts...).ToFunc()
}

// ByImageDownloadError orders the results by the image_download_error field.
func ByImageDownloadError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageDownloadError, opts...).ToFunc()
}

// ByPromptHash orders the results by the prompt_hash field.
func ByPromptHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptHash, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// BySourceName orders the results by the source_name field.
func BySourceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceName, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByLicense orders the results by the license field.
func ByLicense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicense, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByMeta orders the results by the meta field.
func ByMeta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeta, opts...).ToFunc()
}

// ByRequiresReference orders the results by the requires_reference field.
func ByRequiresReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiresReference, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}
