// Code generated by ent, DO NOT EDIT.

package imagestudiotemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldKey, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldMode, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldTitle, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldModel, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImage, v))
}

// OriginalImageURL applies equality check predicate on the "original_image_url" field. It's identical to OriginalImageURLEQ.
func OriginalImageURL(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldOriginalImageURL, v))
}

// ImageHash applies equality check predicate on the "image_hash" field. It's identical to ImageHashEQ.
func ImageHash(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImageHash, v))
}

// ImageDownloadError applies equality check predicate on the "image_download_error" field. It's identical to ImageDownloadErrorEQ.
func ImageDownloadError(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImageDownloadError, v))
}

// PromptHash applies equality check predicate on the "prompt_hash" field. It's identical to PromptHashEQ.
func PromptHash(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldPromptHash, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldPrompt, v))
}

// SourceName applies equality check predicate on the "source_name" field. It's identical to SourceNameEQ.
func SourceName(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceName, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceURL, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceType, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldLicense, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldAuthor, v))
}

// Meta applies equality check predicate on the "meta" field. It's identical to MetaEQ.
func Meta(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldMeta, v))
}

// RequiresReference applies equality check predicate on the "requires_reference" field. It's identical to RequiresReferenceEQ.
func RequiresReference(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldRequiresReference, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldKey, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldMode, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldTitle, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldModel, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldImage, v))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldImage, v))
}

// OriginalImageURLEQ applies the EQ predicate on the "original_image_url" field.
func OriginalImageURLEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldOriginalImageURL, v))
}

// OriginalImageURLNEQ applies the NEQ predicate on the "original_image_url" field.
func OriginalImageURLNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldOriginalImageURL, v))
}

// OriginalImageURLIn applies the In predicate on the "original_image_url" field.
func OriginalImageURLIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldOriginalImageURL, vs...))
}

// OriginalImageURLNotIn applies the NotIn predicate on the "original_image_url" field.
func OriginalImageURLNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldOriginalImageURL, vs...))
}

// OriginalImageURLGT applies the GT predicate on the "original_image_url" field.
func OriginalImageURLGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldOriginalImageURL, v))
}

// OriginalImageURLGTE applies the GTE predicate on the "original_image_url" field.
func OriginalImageURLGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldOriginalImageURL, v))
}

// OriginalImageURLLT applies the LT predicate on the "original_image_url" field.
func OriginalImageURLLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldOriginalImageURL, v))
}

// OriginalImageURLLTE applies the LTE predicate on the "original_image_url" field.
func OriginalImageURLLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldOriginalImageURL, v))
}

// OriginalImageURLContains applies the Contains predicate on the "original_image_url" field.
func OriginalImageURLContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldOriginalImageURL, v))
}

// OriginalImageURLHasPrefix applies the HasPrefix predicate on the "original_image_url" field.
func OriginalImageURLHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldOriginalImageURL, v))
}

// OriginalImageURLHasSuffix applies the HasSuffix predicate on the "original_image_url" field.
func OriginalImageURLHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldOriginalImageURL, v))
}

// OriginalImageURLIsNil applies the IsNil predicate on the "original_image_url" field.
func OriginalImageURLIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldOriginalImageURL))
}

// OriginalImageURLNotNil applies the NotNil predicate on the "original_image_url" field.
func OriginalImageURLNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldOriginalImageURL))
}

// OriginalImageURLEqualFold applies the EqualFold predicate on the "original_image_url" field.
func OriginalImageURLEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldOriginalImageURL, v))
}

// OriginalImageURLContainsFold applies the ContainsFold predicate on the "original_image_url" field.
func OriginalImageURLContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldOriginalImageURL, v))
}

// ImageHashEQ applies the EQ predicate on the "image_hash" field.
func ImageHashEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImageHash, v))
}

// ImageHashNEQ applies the NEQ predicate on the "image_hash" field.
func ImageHashNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldImageHash, v))
}

// ImageHashIn applies the In predicate on the "image_hash" field.
func ImageHashIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldImageHash, vs...))
}

// ImageHashNotIn applies the NotIn predicate on the "image_hash" field.
func ImageHashNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldImageHash, vs...))
}

// ImageHashGT applies the GT predicate on the "image_hash" field.
func ImageHashGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldImageHash, v))
}

// ImageHashGTE applies the GTE predicate on the "image_hash" field.
func ImageHashGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldImageHash, v))
}

// ImageHashLT applies the LT predicate on the "image_hash" field.
func ImageHashLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldImageHash, v))
}

// ImageHashLTE applies the LTE predicate on the "image_hash" field.
func ImageHashLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldImageHash, v))
}

// ImageHashContains applies the Contains predicate on the "image_hash" field.
func ImageHashContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldImageHash, v))
}

// ImageHashHasPrefix applies the HasPrefix predicate on the "image_hash" field.
func ImageHashHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldImageHash, v))
}

// ImageHashHasSuffix applies the HasSuffix predicate on the "image_hash" field.
func ImageHashHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldImageHash, v))
}

// ImageHashIsNil applies the IsNil predicate on the "image_hash" field.
func ImageHashIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldImageHash))
}

// ImageHashNotNil applies the NotNil predicate on the "image_hash" field.
func ImageHashNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldImageHash))
}

// ImageHashEqualFold applies the EqualFold predicate on the "image_hash" field.
func ImageHashEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldImageHash, v))
}

// ImageHashContainsFold applies the ContainsFold predicate on the "image_hash" field.
func ImageHashContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldImageHash, v))
}

// ImageDownloadErrorEQ applies the EQ predicate on the "image_download_error" field.
func ImageDownloadErrorEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldImageDownloadError, v))
}

// ImageDownloadErrorNEQ applies the NEQ predicate on the "image_download_error" field.
func ImageDownloadErrorNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldImageDownloadError, v))
}

// ImageDownloadErrorIn applies the In predicate on the "image_download_error" field.
func ImageDownloadErrorIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldImageDownloadError, vs...))
}

// ImageDownloadErrorNotIn applies the NotIn predicate on the "image_download_error" field.
func ImageDownloadErrorNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldImageDownloadError, vs...))
}

// ImageDownloadErrorGT applies the GT predicate on the "image_download_error" field.
func ImageDownloadErrorGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldImageDownloadError, v))
}

// ImageDownloadErrorGTE applies the GTE predicate on the "image_download_error" field.
func ImageDownloadErrorGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldImageDownloadError, v))
}

// ImageDownloadErrorLT applies the LT predicate on the "image_download_error" field.
func ImageDownloadErrorLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldImageDownloadError, v))
}

// ImageDownloadErrorLTE applies the LTE predicate on the "image_download_error" field.
func ImageDownloadErrorLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldImageDownloadError, v))
}

// ImageDownloadErrorContains applies the Contains predicate on the "image_download_error" field.
func ImageDownloadErrorContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldImageDownloadError, v))
}

// ImageDownloadErrorHasPrefix applies the HasPrefix predicate on the "image_download_error" field.
func ImageDownloadErrorHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldImageDownloadError, v))
}

// ImageDownloadErrorHasSuffix applies the HasSuffix predicate on the "image_download_error" field.
func ImageDownloadErrorHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldImageDownloadError, v))
}

// ImageDownloadErrorIsNil applies the IsNil predicate on the "image_download_error" field.
func ImageDownloadErrorIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldImageDownloadError))
}

// ImageDownloadErrorNotNil applies the NotNil predicate on the "image_download_error" field.
func ImageDownloadErrorNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldImageDownloadError))
}

// ImageDownloadErrorEqualFold applies the EqualFold predicate on the "image_download_error" field.
func ImageDownloadErrorEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldImageDownloadError, v))
}

// ImageDownloadErrorContainsFold applies the ContainsFold predicate on the "image_download_error" field.
func ImageDownloadErrorContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldImageDownloadError, v))
}

// PromptHashEQ applies the EQ predicate on the "prompt_hash" field.
func PromptHashEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldPromptHash, v))
}

// PromptHashNEQ applies the NEQ predicate on the "prompt_hash" field.
func PromptHashNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldPromptHash, v))
}

// PromptHashIn applies the In predicate on the "prompt_hash" field.
func PromptHashIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldPromptHash, vs...))
}

// PromptHashNotIn applies the NotIn predicate on the "prompt_hash" field.
func PromptHashNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldPromptHash, vs...))
}

// PromptHashGT applies the GT predicate on the "prompt_hash" field.
func PromptHashGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldPromptHash, v))
}

// PromptHashGTE applies the GTE predicate on the "prompt_hash" field.
func PromptHashGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldPromptHash, v))
}

// PromptHashLT applies the LT predicate on the "prompt_hash" field.
func PromptHashLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldPromptHash, v))
}

// PromptHashLTE applies the LTE predicate on the "prompt_hash" field.
func PromptHashLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldPromptHash, v))
}

// PromptHashContains applies the Contains predicate on the "prompt_hash" field.
func PromptHashContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldPromptHash, v))
}

// PromptHashHasPrefix applies the HasPrefix predicate on the "prompt_hash" field.
func PromptHashHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldPromptHash, v))
}

// PromptHashHasSuffix applies the HasSuffix predicate on the "prompt_hash" field.
func PromptHashHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldPromptHash, v))
}

// PromptHashIsNil applies the IsNil predicate on the "prompt_hash" field.
func PromptHashIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldPromptHash))
}

// PromptHashNotNil applies the NotNil predicate on the "prompt_hash" field.
func PromptHashNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldPromptHash))
}

// PromptHashEqualFold applies the EqualFold predicate on the "prompt_hash" field.
func PromptHashEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldPromptHash, v))
}

// PromptHashContainsFold applies the ContainsFold predicate on the "prompt_hash" field.
func PromptHashContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldPromptHash, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldPrompt, v))
}

// SourceNameEQ applies the EQ predicate on the "source_name" field.
func SourceNameEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceName, v))
}

// SourceNameNEQ applies the NEQ predicate on the "source_name" field.
func SourceNameNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldSourceName, v))
}

// SourceNameIn applies the In predicate on the "source_name" field.
func SourceNameIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldSourceName, vs...))
}

// SourceNameNotIn applies the NotIn predicate on the "source_name" field.
func SourceNameNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldSourceName, vs...))
}

// SourceNameGT applies the GT predicate on the "source_name" field.
func SourceNameGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldSourceName, v))
}

// SourceNameGTE applies the GTE predicate on the "source_name" field.
func SourceNameGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldSourceName, v))
}

// SourceNameLT applies the LT predicate on the "source_name" field.
func SourceNameLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldSourceName, v))
}

// SourceNameLTE applies the LTE predicate on the "source_name" field.
func SourceNameLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldSourceName, v))
}

// SourceNameContains applies the Contains predicate on the "source_name" field.
func SourceNameContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldSourceName, v))
}

// SourceNameHasPrefix applies the HasPrefix predicate on the "source_name" field.
func SourceNameHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldSourceName, v))
}

// SourceNameHasSuffix applies the HasSuffix predicate on the "source_name" field.
func SourceNameHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldSourceName, v))
}

// SourceNameIsNil applies the IsNil predicate on the "source_name" field.
func SourceNameIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldSourceName))
}

// SourceNameNotNil applies the NotNil predicate on the "source_name" field.
func SourceNameNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldSourceName))
}

// SourceNameEqualFold applies the EqualFold predicate on the "source_name" field.
func SourceNameEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldSourceName, v))
}

// SourceNameContainsFold applies the ContainsFold predicate on the "source_name" field.
func SourceNameContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldSourceName, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldSourceURL, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeIsNil applies the IsNil predicate on the "source_type" field.
func SourceTypeIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldSourceType))
}

// SourceTypeNotNil applies the NotNil predicate on the "source_type" field.
func SourceTypeNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldSourceType))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldSourceType, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseIsNil applies the IsNil predicate on the "license" field.
func LicenseIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldLicense))
}

// LicenseNotNil applies the NotNil predicate on the "license" field.
func LicenseNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldLicense))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldLicense, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorIsNil applies the IsNil predicate on the "author" field.
func AuthorIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldAuthor))
}

// AuthorNotNil applies the NotNil predicate on the "author" field.
func AuthorNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldAuthor))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldAuthor, v))
}

// MetaEQ applies the EQ predicate on the "meta" field.
func MetaEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldMeta, v))
}

// MetaNEQ applies the NEQ predicate on the "meta" field.
func MetaNEQ(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldMeta, v))
}

// MetaIn applies the In predicate on the "meta" field.
func MetaIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldMeta, vs...))
}

// MetaNotIn applies the NotIn predicate on the "meta" field.
func MetaNotIn(vs ...string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldMeta, vs...))
}

// MetaGT applies the GT predicate on the "meta" field.
func MetaGT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldMeta, v))
}

// MetaGTE applies the GTE predicate on the "meta" field.
func MetaGTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldMeta, v))
}

// MetaLT applies the LT predicate on the "meta" field.
func MetaLT(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldMeta, v))
}

// MetaLTE applies the LTE predicate on the "meta" field.
func MetaLTE(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldMeta, v))
}

// MetaContains applies the Contains predicate on the "meta" field.
func MetaContains(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContains(FieldMeta, v))
}

// MetaHasPrefix applies the HasPrefix predicate on the "meta" field.
func MetaHasPrefix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasPrefix(FieldMeta, v))
}

// MetaHasSuffix applies the HasSuffix predicate on the "meta" field.
func MetaHasSuffix(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldHasSuffix(FieldMeta, v))
}

// MetaIsNil applies the IsNil predicate on the "meta" field.
func MetaIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldMeta))
}

// MetaNotNil applies the NotNil predicate on the "meta" field.
func MetaNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldMeta))
}

// MetaEqualFold applies the EqualFold predicate on the "meta" field.
func MetaEqualFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEqualFold(FieldMeta, v))
}

// MetaContainsFold applies the ContainsFold predicate on the "meta" field.
func MetaContainsFold(v string) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldContainsFold(FieldMeta, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotNull(FieldTags))
}

// RequiresReferenceEQ applies the EQ predicate on the "requires_reference" field.
func RequiresReferenceEQ(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldRequiresReference, v))
}

// RequiresReferenceNEQ applies the NEQ predicate on the "requires_reference" field.
func RequiresReferenceNEQ(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldRequiresReference, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.FieldLTE(FieldSortOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageStudioTemplate) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageStudioTemplate) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageStudioTemplate) predicate.ImageStudioTemplate {
	return predicate.ImageStudioTemplate(sql.NotPredicates(p))
}
