// Code generated by ent, DO NOT EDIT.

package benefitclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldUpdatedAt, v))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldCampaignID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldStatus, v))
}

// EligibleRechargeAmount applies equality check predicate on the "eligible_recharge_amount" field. It's identical to EligibleRechargeAmountEQ.
func EligibleRechargeAmount(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldEligibleRechargeAmount, v))
}

// GrantedAmount applies equality check predicate on the "granted_amount" field. It's identical to GrantedAmountEQ.
func GrantedAmount(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldGrantedAmount, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldBalanceAfter, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// SourceRedeemCode applies equality check predicate on the "source_redeem_code" field. It's identical to SourceRedeemCodeEQ.
func SourceRedeemCode(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldSourceRedeemCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldUpdatedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldCampaignID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldUserID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldContainsFold(FieldStatus, v))
}

// EligibleRechargeAmountEQ applies the EQ predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldEligibleRechargeAmount, v))
}

// EligibleRechargeAmountNEQ applies the NEQ predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountNEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldEligibleRechargeAmount, v))
}

// EligibleRechargeAmountIn applies the In predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldEligibleRechargeAmount, vs...))
}

// EligibleRechargeAmountNotIn applies the NotIn predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountNotIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldEligibleRechargeAmount, vs...))
}

// EligibleRechargeAmountGT applies the GT predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountGT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldEligibleRechargeAmount, v))
}

// EligibleRechargeAmountGTE applies the GTE predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountGTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldEligibleRechargeAmount, v))
}

// EligibleRechargeAmountLT applies the LT predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountLT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldEligibleRechargeAmount, v))
}

// EligibleRechargeAmountLTE applies the LTE predicate on the "eligible_recharge_amount" field.
func EligibleRechargeAmountLTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldEligibleRechargeAmount, v))
}

// GrantedAmountEQ applies the EQ predicate on the "granted_amount" field.
func GrantedAmountEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldGrantedAmount, v))
}

// GrantedAmountNEQ applies the NEQ predicate on the "granted_amount" field.
func GrantedAmountNEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldGrantedAmount, v))
}

// GrantedAmountIn applies the In predicate on the "granted_amount" field.
func GrantedAmountIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldGrantedAmount, vs...))
}

// GrantedAmountNotIn applies the NotIn predicate on the "granted_amount" field.
func GrantedAmountNotIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldGrantedAmount, vs...))
}

// GrantedAmountGT applies the GT predicate on the "granted_amount" field.
func GrantedAmountGT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldGrantedAmount, v))
}

// GrantedAmountGTE applies the GTE predicate on the "granted_amount" field.
func GrantedAmountGTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldGrantedAmount, v))
}

// GrantedAmountLT applies the LT predicate on the "granted_amount" field.
func GrantedAmountLT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldGrantedAmount, v))
}

// GrantedAmountLTE applies the LTE predicate on the "granted_amount" field.
func GrantedAmountLTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldGrantedAmount, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldBalanceAfter, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldClaimedAt, v))
}

// SourceRedeemCodeEQ applies the EQ predicate on the "source_redeem_code" field.
func SourceRedeemCodeEQ(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEQ(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeNEQ applies the NEQ predicate on the "source_redeem_code" field.
func SourceRedeemCodeNEQ(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNEQ(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeIn applies the In predicate on the "source_redeem_code" field.
func SourceRedeemCodeIn(vs ...string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIn(FieldSourceRedeemCode, vs...))
}

// SourceRedeemCodeNotIn applies the NotIn predicate on the "source_redeem_code" field.
func SourceRedeemCodeNotIn(vs ...string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotIn(FieldSourceRedeemCode, vs...))
}

// SourceRedeemCodeGT applies the GT predicate on the "source_redeem_code" field.
func SourceRedeemCodeGT(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGT(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeGTE applies the GTE predicate on the "source_redeem_code" field.
func SourceRedeemCodeGTE(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldGTE(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeLT applies the LT predicate on the "source_redeem_code" field.
func SourceRedeemCodeLT(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLT(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeLTE applies the LTE predicate on the "source_redeem_code" field.
func SourceRedeemCodeLTE(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldLTE(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeContains applies the Contains predicate on the "source_redeem_code" field.
func SourceRedeemCodeContains(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldContains(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeHasPrefix applies the HasPrefix predicate on the "source_redeem_code" field.
func SourceRedeemCodeHasPrefix(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldHasPrefix(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeHasSuffix applies the HasSuffix predicate on the "source_redeem_code" field.
func SourceRedeemCodeHasSuffix(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldHasSuffix(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeIsNil applies the IsNil predicate on the "source_redeem_code" field.
func SourceRedeemCodeIsNil() predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIsNull(FieldSourceRedeemCode))
}

// SourceRedeemCodeNotNil applies the NotNil predicate on the "source_redeem_code" field.
func SourceRedeemCodeNotNil() predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotNull(FieldSourceRedeemCode))
}

// SourceRedeemCodeEqualFold applies the EqualFold predicate on the "source_redeem_code" field.
func SourceRedeemCodeEqualFold(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldEqualFold(FieldSourceRedeemCode, v))
}

// SourceRedeemCodeContainsFold applies the ContainsFold predicate on the "source_redeem_code" field.
func SourceRedeemCodeContainsFold(v string) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldContainsFold(FieldSourceRedeemCode, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.FieldNotNull(FieldMetadata))
}

// HasCampaign applies the HasEdge predicate on the "campaign" edge.
func HasCampaign() predicate.BenefitClaim {
	return predicate.BenefitClaim(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CampaignTable, CampaignColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCampaignWith applies the HasEdge predicate on the "campaign" edge with a given conditions (other predicates).
func HasCampaignWith(preds ...predicate.BenefitCampaign) predicate.BenefitClaim {
	return predicate.BenefitClaim(func(s *sql.Selector) {
		step := newCampaignStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BenefitClaim {
	return predicate.BenefitClaim(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BenefitClaim {
	return predicate.BenefitClaim(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BenefitClaim) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BenefitClaim) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BenefitClaim) predicate.BenefitClaim {
	return predicate.BenefitClaim(sql.NotPredicates(p))
}
