// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BenefitCampaignUpdate is the builder for updating BenefitCampaign entities.
type BenefitCampaignUpdate struct {
	config
	hooks    []Hook
	mutation *BenefitCampaignMutation
}

// Where appends a list predicates to the BenefitCampaignUpdate builder.
func (_u *BenefitCampaignUpdate) Where(ps ...predicate.BenefitCampaign) *BenefitCampaignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitCampaignUpdate) SetUpdatedAt(v time.Time) *BenefitCampaignUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BenefitCampaignUpdate) SetDeletedAt(v time.Time) *BenefitCampaignUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableDeletedAt(v *time.Time) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BenefitCampaignUpdate) ClearDeletedAt() *BenefitCampaignUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *BenefitCampaignUpdate) SetName(v string) *BenefitCampaignUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableName(v *string) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BenefitCampaignUpdate) SetEnabled(v bool) *BenefitCampaignUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableEnabled(v *bool) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *BenefitCampaignUpdate) SetVisible(v bool) *BenefitCampaignUpdate {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableVisible(v *bool) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *BenefitCampaignUpdate) SetStartsAt(v time.Time) *BenefitCampaignUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableStartsAt(v *time.Time) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *BenefitCampaignUpdate) SetEndsAt(v time.Time) *BenefitCampaignUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableEndsAt(v *time.Time) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetThresholdAmount sets the "threshold_amount" field.
func (_u *BenefitCampaignUpdate) SetThresholdAmount(v float64) *BenefitCampaignUpdate {
	_u.mutation.ResetThresholdAmount()
	_u.mutation.SetThresholdAmount(v)
	return _u
}

// SetNillableThresholdAmount sets the "threshold_amount" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableThresholdAmount(v *float64) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetThresholdAmount(*v)
	}
	return _u
}

// AddThresholdAmount adds value to the "threshold_amount" field.
func (_u *BenefitCampaignUpdate) AddThresholdAmount(v float64) *BenefitCampaignUpdate {
	_u.mutation.AddThresholdAmount(v)
	return _u
}

// SetGrantAmount sets the "grant_amount" field.
func (_u *BenefitCampaignUpdate) SetGrantAmount(v float64) *BenefitCampaignUpdate {
	_u.mutation.ResetGrantAmount()
	_u.mutation.SetGrantAmount(v)
	return _u
}

// SetNillableGrantAmount sets the "grant_amount" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableGrantAmount(v *float64) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetGrantAmount(*v)
	}
	return _u
}

// AddGrantAmount adds value to the "grant_amount" field.
func (_u *BenefitCampaignUpdate) AddGrantAmount(v float64) *BenefitCampaignUpdate {
	_u.mutation.AddGrantAmount(v)
	return _u
}

// SetRechargeScope sets the "recharge_scope" field.
func (_u *BenefitCampaignUpdate) SetRechargeScope(v string) *BenefitCampaignUpdate {
	_u.mutation.SetRechargeScope(v)
	return _u
}

// SetNillableRechargeScope sets the "recharge_scope" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableRechargeScope(v *string) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetRechargeScope(*v)
	}
	return _u
}

// SetCopy sets the "copy" field.
func (_u *BenefitCampaignUpdate) SetCopy(v map[string]string) *BenefitCampaignUpdate {
	_u.mutation.SetCopy(v)
	return _u
}

// ClearCopy clears the value of the "copy" field.
func (_u *BenefitCampaignUpdate) ClearCopy() *BenefitCampaignUpdate {
	_u.mutation.ClearCopy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BenefitCampaignUpdate) SetSortOrder(v int) *BenefitCampaignUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BenefitCampaignUpdate) SetNillableSortOrder(v *int) *BenefitCampaignUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BenefitCampaignUpdate) AddSortOrder(v int) *BenefitCampaignUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddClaimIDs adds the "claims" edge to the BenefitClaim entity by IDs.
func (_u *BenefitCampaignUpdate) AddClaimIDs(ids ...int64) *BenefitCampaignUpdate {
	_u.mutation.AddClaimIDs(ids...)
	return _u
}

// AddClaims adds the "claims" edges to the BenefitClaim entity.
func (_u *BenefitCampaignUpdate) AddClaims(v ...*BenefitClaim) *BenefitCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimIDs(ids...)
}

// Mutation returns the BenefitCampaignMutation object of the builder.
func (_u *BenefitCampaignUpdate) Mutation() *BenefitCampaignMutation {
	return _u.mutation
}

// ClearClaims clears all "claims" edges to the BenefitClaim entity.
func (_u *BenefitCampaignUpdate) ClearClaims() *BenefitCampaignUpdate {
	_u.mutation.ClearClaims()
	return _u
}

// RemoveClaimIDs removes the "claims" edge to BenefitClaim entities by IDs.
func (_u *BenefitCampaignUpdate) RemoveClaimIDs(ids ...int64) *BenefitCampaignUpdate {
	_u.mutation.RemoveClaimIDs(ids...)
	return _u
}

// RemoveClaims removes "claims" edges to BenefitClaim entities.
func (_u *BenefitCampaignUpdate) RemoveClaims(v ...*BenefitClaim) *BenefitCampaignUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitCampaignUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitCampaignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitCampaignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitCampaignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitCampaignUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if benefitcampaign.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized benefitcampaign.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := benefitcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitCampaignUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := benefitcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeScope(); ok {
		if err := benefitcampaign.RechargeScopeValidator(v); err != nil {
			return &ValidationError{Name: "recharge_scope", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.recharge_scope": %w`, err)}
		}
	}
	return nil
}

func (_u *BenefitCampaignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitcampaign.Table, benefitcampaign.Columns, sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(benefitcampaign.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(benefitcampaign.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(benefitcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(benefitcampaign.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(benefitcampaign.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(benefitcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(benefitcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ThresholdAmount(); ok {
		_spec.SetField(benefitcampaign.FieldThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThresholdAmount(); ok {
		_spec.AddField(benefitcampaign.FieldThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantAmount(); ok {
		_spec.SetField(benefitcampaign.FieldGrantAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantAmount(); ok {
		_spec.AddField(benefitcampaign.FieldGrantAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeScope(); ok {
		_spec.SetField(benefitcampaign.FieldRechargeScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Copy(); ok {
		_spec.SetField(benefitcampaign.FieldCopy, field.TypeJSON, value)
	}
	if _u.mutation.CopyCleared() {
		_spec.ClearField(benefitcampaign.FieldCopy, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(benefitcampaign.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(benefitcampaign.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimsIDs(); len(nodes) > 0 && !_u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitCampaignUpdateOne is the builder for updating a single BenefitCampaign entity.
type BenefitCampaignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BenefitCampaignMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitCampaignUpdateOne) SetUpdatedAt(v time.Time) *BenefitCampaignUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BenefitCampaignUpdateOne) SetDeletedAt(v time.Time) *BenefitCampaignUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableDeletedAt(v *time.Time) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BenefitCampaignUpdateOne) ClearDeletedAt() *BenefitCampaignUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *BenefitCampaignUpdateOne) SetName(v string) *BenefitCampaignUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableName(v *string) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BenefitCampaignUpdateOne) SetEnabled(v bool) *BenefitCampaignUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableEnabled(v *bool) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *BenefitCampaignUpdateOne) SetVisible(v bool) *BenefitCampaignUpdateOne {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableVisible(v *bool) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *BenefitCampaignUpdateOne) SetStartsAt(v time.Time) *BenefitCampaignUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableStartsAt(v *time.Time) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *BenefitCampaignUpdateOne) SetEndsAt(v time.Time) *BenefitCampaignUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableEndsAt(v *time.Time) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetThresholdAmount sets the "threshold_amount" field.
func (_u *BenefitCampaignUpdateOne) SetThresholdAmount(v float64) *BenefitCampaignUpdateOne {
	_u.mutation.ResetThresholdAmount()
	_u.mutation.SetThresholdAmount(v)
	return _u
}

// SetNillableThresholdAmount sets the "threshold_amount" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableThresholdAmount(v *float64) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetThresholdAmount(*v)
	}
	return _u
}

// AddThresholdAmount adds value to the "threshold_amount" field.
func (_u *BenefitCampaignUpdateOne) AddThresholdAmount(v float64) *BenefitCampaignUpdateOne {
	_u.mutation.AddThresholdAmount(v)
	return _u
}

// SetGrantAmount sets the "grant_amount" field.
func (_u *BenefitCampaignUpdateOne) SetGrantAmount(v float64) *BenefitCampaignUpdateOne {
	_u.mutation.ResetGrantAmount()
	_u.mutation.SetGrantAmount(v)
	return _u
}

// SetNillableGrantAmount sets the "grant_amount" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableGrantAmount(v *float64) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetGrantAmount(*v)
	}
	return _u
}

// AddGrantAmount adds value to the "grant_amount" field.
func (_u *BenefitCampaignUpdateOne) AddGrantAmount(v float64) *BenefitCampaignUpdateOne {
	_u.mutation.AddGrantAmount(v)
	return _u
}

// SetRechargeScope sets the "recharge_scope" field.
func (_u *BenefitCampaignUpdateOne) SetRechargeScope(v string) *BenefitCampaignUpdateOne {
	_u.mutation.SetRechargeScope(v)
	return _u
}

// SetNillableRechargeScope sets the "recharge_scope" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableRechargeScope(v *string) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetRechargeScope(*v)
	}
	return _u
}

// SetCopy sets the "copy" field.
func (_u *BenefitCampaignUpdateOne) SetCopy(v map[string]string) *BenefitCampaignUpdateOne {
	_u.mutation.SetCopy(v)
	return _u
}

// ClearCopy clears the value of the "copy" field.
func (_u *BenefitCampaignUpdateOne) ClearCopy() *BenefitCampaignUpdateOne {
	_u.mutation.ClearCopy()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BenefitCampaignUpdateOne) SetSortOrder(v int) *BenefitCampaignUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BenefitCampaignUpdateOne) SetNillableSortOrder(v *int) *BenefitCampaignUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BenefitCampaignUpdateOne) AddSortOrder(v int) *BenefitCampaignUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddClaimIDs adds the "claims" edge to the BenefitClaim entity by IDs.
func (_u *BenefitCampaignUpdateOne) AddClaimIDs(ids ...int64) *BenefitCampaignUpdateOne {
	_u.mutation.AddClaimIDs(ids...)
	return _u
}

// AddClaims adds the "claims" edges to the BenefitClaim entity.
func (_u *BenefitCampaignUpdateOne) AddClaims(v ...*BenefitClaim) *BenefitCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClaimIDs(ids...)
}

// Mutation returns the BenefitCampaignMutation object of the builder.
func (_u *BenefitCampaignUpdateOne) Mutation() *BenefitCampaignMutation {
	return _u.mutation
}

// ClearClaims clears all "claims" edges to the BenefitClaim entity.
func (_u *BenefitCampaignUpdateOne) ClearClaims() *BenefitCampaignUpdateOne {
	_u.mutation.ClearClaims()
	return _u
}

// RemoveClaimIDs removes the "claims" edge to BenefitClaim entities by IDs.
func (_u *BenefitCampaignUpdateOne) RemoveClaimIDs(ids ...int64) *BenefitCampaignUpdateOne {
	_u.mutation.RemoveClaimIDs(ids...)
	return _u
}

// RemoveClaims removes "claims" edges to BenefitClaim entities.
func (_u *BenefitCampaignUpdateOne) RemoveClaims(v ...*BenefitClaim) *BenefitCampaignUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClaimIDs(ids...)
}

// Where appends a list predicates to the BenefitCampaignUpdate builder.
func (_u *BenefitCampaignUpdateOne) Where(ps ...predicate.BenefitCampaign) *BenefitCampaignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitCampaignUpdateOne) Select(field string, fields ...string) *BenefitCampaignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BenefitCampaign entity.
func (_u *BenefitCampaignUpdateOne) Save(ctx context.Context) (*BenefitCampaign, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitCampaignUpdateOne) SaveX(ctx context.Context) *BenefitCampaign {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitCampaignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitCampaignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitCampaignUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if benefitcampaign.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized benefitcampaign.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := benefitcampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitCampaignUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := benefitcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeScope(); ok {
		if err := benefitcampaign.RechargeScopeValidator(v); err != nil {
			return &ValidationError{Name: "recharge_scope", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.recharge_scope": %w`, err)}
		}
	}
	return nil
}

func (_u *BenefitCampaignUpdateOne) sqlSave(ctx context.Context) (_node *BenefitCampaign, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitcampaign.Table, benefitcampaign.Columns, sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitCampaign.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitcampaign.FieldID)
		for _, f := range fields {
			if !benefitcampaign.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitcampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitcampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(benefitcampaign.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(benefitcampaign.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(benefitcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(benefitcampaign.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(benefitcampaign.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(benefitcampaign.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(benefitcampaign.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ThresholdAmount(); ok {
		_spec.SetField(benefitcampaign.FieldThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThresholdAmount(); ok {
		_spec.AddField(benefitcampaign.FieldThresholdAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantAmount(); ok {
		_spec.SetField(benefitcampaign.FieldGrantAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantAmount(); ok {
		_spec.AddField(benefitcampaign.FieldGrantAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RechargeScope(); ok {
		_spec.SetField(benefitcampaign.FieldRechargeScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Copy(); ok {
		_spec.SetField(benefitcampaign.FieldCopy, field.TypeJSON, value)
	}
	if _u.mutation.CopyCleared() {
		_spec.ClearField(benefitcampaign.FieldCopy, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(benefitcampaign.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(benefitcampaign.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClaimsIDs(); len(nodes) > 0 && !_u.mutation.ClaimsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BenefitCampaign{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
