// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BenefitClaimCreate is the builder for creating a BenefitClaim entity.
type BenefitClaimCreate struct {
	config
	mutation *BenefitClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BenefitClaimCreate) SetCreatedAt(v time.Time) *BenefitClaimCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BenefitClaimCreate) SetNillableCreatedAt(v *time.Time) *BenefitClaimCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BenefitClaimCreate) SetUpdatedAt(v time.Time) *BenefitClaimCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BenefitClaimCreate) SetNillableUpdatedAt(v *time.Time) *BenefitClaimCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCampaignID sets the "campaign_id" field.
func (_c *BenefitClaimCreate) SetCampaignID(v int64) *BenefitClaimCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BenefitClaimCreate) SetUserID(v int64) *BenefitClaimCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BenefitClaimCreate) SetStatus(v string) *BenefitClaimCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BenefitClaimCreate) SetNillableStatus(v *string) *BenefitClaimCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (_c *BenefitClaimCreate) SetEligibleRechargeAmount(v float64) *BenefitClaimCreate {
	_c.mutation.SetEligibleRechargeAmount(v)
	return _c
}

// SetGrantedAmount sets the "granted_amount" field.
func (_c *BenefitClaimCreate) SetGrantedAmount(v float64) *BenefitClaimCreate {
	_c.mutation.SetGrantedAmount(v)
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *BenefitClaimCreate) SetBalanceBefore(v float64) *BenefitClaimCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *BenefitClaimCreate) SetBalanceAfter(v float64) *BenefitClaimCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *BenefitClaimCreate) SetClaimedAt(v time.Time) *BenefitClaimCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_c *BenefitClaimCreate) SetSourceRedeemCode(v string) *BenefitClaimCreate {
	_c.mutation.SetSourceRedeemCode(v)
	return _c
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_c *BenefitClaimCreate) SetNillableSourceRedeemCode(v *string) *BenefitClaimCreate {
	if v != nil {
		_c.SetSourceRedeemCode(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *BenefitClaimCreate) SetMetadata(v map[string]interface{}) *BenefitClaimCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCampaign sets the "campaign" edge to the BenefitCampaign entity.
func (_c *BenefitClaimCreate) SetCampaign(v *BenefitCampaign) *BenefitClaimCreate {
	return _c.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *BenefitClaimCreate) SetUser(v *User) *BenefitClaimCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the BenefitClaimMutation object of the builder.
func (_c *BenefitClaimCreate) Mutation() *BenefitClaimMutation {
	return _c.mutation
}

// Save creates the BenefitClaim in the database.
func (_c *BenefitClaimCreate) Save(ctx context.Context) (*BenefitClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BenefitClaimCreate) SaveX(ctx context.Context) *BenefitClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BenefitClaimCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := benefitclaim.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := benefitclaim.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := benefitclaim.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BenefitClaimCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BenefitClaim.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BenefitClaim.updated_at"`)}
	}
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "BenefitClaim.campaign_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BenefitClaim.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BenefitClaim.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := benefitclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EligibleRechargeAmount(); !ok {
		return &ValidationError{Name: "eligible_recharge_amount", err: errors.New(`ent: missing required field "BenefitClaim.eligible_recharge_amount"`)}
	}
	if _, ok := _c.mutation.GrantedAmount(); !ok {
		return &ValidationError{Name: "granted_amount", err: errors.New(`ent: missing required field "BenefitClaim.granted_amount"`)}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "BenefitClaim.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "BenefitClaim.balance_after"`)}
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		return &ValidationError{Name: "claimed_at", err: errors.New(`ent: missing required field "BenefitClaim.claimed_at"`)}
	}
	if v, ok := _c.mutation.SourceRedeemCode(); ok {
		if err := benefitclaim.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.source_redeem_code": %w`, err)}
		}
	}
	if len(_c.mutation.CampaignIDs()) == 0 {
		return &ValidationError{Name: "campaign", err: errors.New(`ent: missing required edge "BenefitClaim.campaign"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "BenefitClaim.user"`)}
	}
	return nil
}

func (_c *BenefitClaimCreate) sqlSave(ctx context.Context) (*BenefitClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BenefitClaimCreate) createSpec() (*BenefitClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &BenefitClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(benefitclaim.Table, sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(benefitclaim.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitclaim.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(benefitclaim.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EligibleRechargeAmount(); ok {
		_spec.SetField(benefitclaim.FieldEligibleRechargeAmount, field.TypeFloat64, value)
		_node.EligibleRechargeAmount = value
	}
	if value, ok := _c.mutation.GrantedAmount(); ok {
		_spec.SetField(benefitclaim.FieldGrantedAmount, field.TypeFloat64, value)
		_node.GrantedAmount = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(benefitclaim.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(benefitclaim.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(benefitclaim.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = value
	}
	if value, ok := _c.mutation.SourceRedeemCode(); ok {
		_spec.SetField(benefitclaim.FieldSourceRedeemCode, field.TypeString, value)
		_node.SourceRedeemCode = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(benefitclaim.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.CampaignTable,
			Columns: []string{benefitclaim.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CampaignID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.UserTable,
			Columns: []string{benefitclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BenefitClaim.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BenefitClaimUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BenefitClaimCreate) OnConflict(opts ...sql.ConflictOption) *BenefitClaimUpsertOne {
	_c.conflict = opts
	return &BenefitClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BenefitClaimCreate) OnConflictColumns(columns ...string) *BenefitClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BenefitClaimUpsertOne{
		create: _c,
	}
}

type (
	// BenefitClaimUpsertOne is the builder for "upsert"-ing
	//  one BenefitClaim node.
	BenefitClaimUpsertOne struct {
		create *BenefitClaimCreate
	}

	// BenefitClaimUpsert is the "OnConflict" setter.
	BenefitClaimUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitClaimUpsert) SetUpdatedAt(v time.Time) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateUpdatedAt() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldUpdatedAt)
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *BenefitClaimUpsert) SetCampaignID(v int64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateCampaignID() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldCampaignID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *BenefitClaimUpsert) SetUserID(v int64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateUserID() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldUserID)
	return u
}

// SetStatus sets the "status" field.
func (u *BenefitClaimUpsert) SetStatus(v string) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateStatus() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldStatus)
	return u
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsert) SetEligibleRechargeAmount(v float64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldEligibleRechargeAmount, v)
	return u
}

// UpdateEligibleRechargeAmount sets the "eligible_recharge_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateEligibleRechargeAmount() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldEligibleRechargeAmount)
	return u
}

// AddEligibleRechargeAmount adds v to the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsert) AddEligibleRechargeAmount(v float64) *BenefitClaimUpsert {
	u.Add(benefitclaim.FieldEligibleRechargeAmount, v)
	return u
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *BenefitClaimUpsert) SetGrantedAmount(v float64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldGrantedAmount, v)
	return u
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateGrantedAmount() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldGrantedAmount)
	return u
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *BenefitClaimUpsert) AddGrantedAmount(v float64) *BenefitClaimUpsert {
	u.Add(benefitclaim.FieldGrantedAmount, v)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BenefitClaimUpsert) SetBalanceBefore(v float64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateBalanceBefore() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldBalanceBefore)
	return u
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BenefitClaimUpsert) AddBalanceBefore(v float64) *BenefitClaimUpsert {
	u.Add(benefitclaim.FieldBalanceBefore, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BenefitClaimUpsert) SetBalanceAfter(v float64) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateBalanceAfter() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BenefitClaimUpsert) AddBalanceAfter(v float64) *BenefitClaimUpsert {
	u.Add(benefitclaim.FieldBalanceAfter, v)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BenefitClaimUpsert) SetClaimedAt(v time.Time) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateClaimedAt() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldClaimedAt)
	return u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *BenefitClaimUpsert) SetSourceRedeemCode(v string) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldSourceRedeemCode, v)
	return u
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateSourceRedeemCode() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldSourceRedeemCode)
	return u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *BenefitClaimUpsert) ClearSourceRedeemCode() *BenefitClaimUpsert {
	u.SetNull(benefitclaim.FieldSourceRedeemCode)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *BenefitClaimUpsert) SetMetadata(v map[string]interface{}) *BenefitClaimUpsert {
	u.Set(benefitclaim.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BenefitClaimUpsert) UpdateMetadata() *BenefitClaimUpsert {
	u.SetExcluded(benefitclaim.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BenefitClaimUpsert) ClearMetadata() *BenefitClaimUpsert {
	u.SetNull(benefitclaim.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BenefitClaimUpsertOne) UpdateNewValues() *BenefitClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(benefitclaim.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BenefitClaimUpsertOne) Ignore() *BenefitClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BenefitClaimUpsertOne) DoNothing() *BenefitClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BenefitClaimCreate.OnConflict
// documentation for more info.
func (u *BenefitClaimUpsertOne) Update(set func(*BenefitClaimUpsert)) *BenefitClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BenefitClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitClaimUpsertOne) SetUpdatedAt(v time.Time) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateUpdatedAt() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCampaignID sets the "campaign_id" field.
func (u *BenefitClaimUpsertOne) SetCampaignID(v int64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateCampaignID() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BenefitClaimUpsertOne) SetUserID(v int64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateUserID() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *BenefitClaimUpsertOne) SetStatus(v string) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateStatus() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsertOne) SetEligibleRechargeAmount(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetEligibleRechargeAmount(v)
	})
}

// AddEligibleRechargeAmount adds v to the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsertOne) AddEligibleRechargeAmount(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddEligibleRechargeAmount(v)
	})
}

// UpdateEligibleRechargeAmount sets the "eligible_recharge_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateEligibleRechargeAmount() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateEligibleRechargeAmount()
	})
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *BenefitClaimUpsertOne) SetGrantedAmount(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetGrantedAmount(v)
	})
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *BenefitClaimUpsertOne) AddGrantedAmount(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddGrantedAmount(v)
	})
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateGrantedAmount() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateGrantedAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BenefitClaimUpsertOne) SetBalanceBefore(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BenefitClaimUpsertOne) AddBalanceBefore(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateBalanceBefore() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BenefitClaimUpsertOne) SetBalanceAfter(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BenefitClaimUpsertOne) AddBalanceAfter(v float64) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateBalanceAfter() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BenefitClaimUpsertOne) SetClaimedAt(v time.Time) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateClaimedAt() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateClaimedAt()
	})
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *BenefitClaimUpsertOne) SetSourceRedeemCode(v string) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetSourceRedeemCode(v)
	})
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateSourceRedeemCode() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateSourceRedeemCode()
	})
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *BenefitClaimUpsertOne) ClearSourceRedeemCode() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.ClearSourceRedeemCode()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BenefitClaimUpsertOne) SetMetadata(v map[string]interface{}) *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BenefitClaimUpsertOne) UpdateMetadata() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BenefitClaimUpsertOne) ClearMetadata() *BenefitClaimUpsertOne {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *BenefitClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BenefitClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BenefitClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BenefitClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BenefitClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BenefitClaimCreateBulk is the builder for creating many BenefitClaim entities in bulk.
type BenefitClaimCreateBulk struct {
	config
	err      error
	builders []*BenefitClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the BenefitClaim entities in the database.
func (_c *BenefitClaimCreateBulk) Save(ctx context.Context) ([]*BenefitClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BenefitClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BenefitClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BenefitClaimCreateBulk) SaveX(ctx context.Context) []*BenefitClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BenefitClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BenefitClaimUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BenefitClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *BenefitClaimUpsertBulk {
	_c.conflict = opts
	return &BenefitClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BenefitClaimCreateBulk) OnConflictColumns(columns ...string) *BenefitClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BenefitClaimUpsertBulk{
		create: _c,
	}
}

// BenefitClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of BenefitClaim nodes.
type BenefitClaimUpsertBulk struct {
	create *BenefitClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BenefitClaimUpsertBulk) UpdateNewValues() *BenefitClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(benefitclaim.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BenefitClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BenefitClaimUpsertBulk) Ignore() *BenefitClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BenefitClaimUpsertBulk) DoNothing() *BenefitClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BenefitClaimCreateBulk.OnConflict
// documentation for more info.
func (u *BenefitClaimUpsertBulk) Update(set func(*BenefitClaimUpsert)) *BenefitClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BenefitClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitClaimUpsertBulk) SetUpdatedAt(v time.Time) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateUpdatedAt() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCampaignID sets the "campaign_id" field.
func (u *BenefitClaimUpsertBulk) SetCampaignID(v int64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateCampaignID() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BenefitClaimUpsertBulk) SetUserID(v int64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateUserID() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *BenefitClaimUpsertBulk) SetStatus(v string) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateStatus() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsertBulk) SetEligibleRechargeAmount(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetEligibleRechargeAmount(v)
	})
}

// AddEligibleRechargeAmount adds v to the "eligible_recharge_amount" field.
func (u *BenefitClaimUpsertBulk) AddEligibleRechargeAmount(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddEligibleRechargeAmount(v)
	})
}

// UpdateEligibleRechargeAmount sets the "eligible_recharge_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateEligibleRechargeAmount() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateEligibleRechargeAmount()
	})
}

// SetGrantedAmount sets the "granted_amount" field.
func (u *BenefitClaimUpsertBulk) SetGrantedAmount(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetGrantedAmount(v)
	})
}

// AddGrantedAmount adds v to the "granted_amount" field.
func (u *BenefitClaimUpsertBulk) AddGrantedAmount(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddGrantedAmount(v)
	})
}

// UpdateGrantedAmount sets the "granted_amount" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateGrantedAmount() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateGrantedAmount()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BenefitClaimUpsertBulk) SetBalanceBefore(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BenefitClaimUpsertBulk) AddBalanceBefore(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateBalanceBefore() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BenefitClaimUpsertBulk) SetBalanceAfter(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BenefitClaimUpsertBulk) AddBalanceAfter(v float64) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateBalanceAfter() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BenefitClaimUpsertBulk) SetClaimedAt(v time.Time) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateClaimedAt() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateClaimedAt()
	})
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (u *BenefitClaimUpsertBulk) SetSourceRedeemCode(v string) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetSourceRedeemCode(v)
	})
}

// UpdateSourceRedeemCode sets the "source_redeem_code" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateSourceRedeemCode() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateSourceRedeemCode()
	})
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (u *BenefitClaimUpsertBulk) ClearSourceRedeemCode() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.ClearSourceRedeemCode()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BenefitClaimUpsertBulk) SetMetadata(v map[string]interface{}) *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BenefitClaimUpsertBulk) UpdateMetadata() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BenefitClaimUpsertBulk) ClearMetadata() *BenefitClaimUpsertBulk {
	return u.Update(func(s *BenefitClaimUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *BenefitClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BenefitClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BenefitClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BenefitClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
