// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BenefitClaimDelete is the builder for deleting a BenefitClaim entity.
type BenefitClaimDelete struct {
	config
	hooks    []Hook
	mutation *BenefitClaimMutation
}

// Where appends a list predicates to the BenefitClaimDelete builder.
func (_d *BenefitClaimDelete) Where(ps ...predicate.BenefitClaim) *BenefitClaimDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BenefitClaimDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitClaimDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BenefitClaimDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(benefitclaim.Table, sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BenefitClaimDeleteOne is the builder for deleting a single BenefitClaim entity.
type BenefitClaimDeleteOne struct {
	_d *BenefitClaimDelete
}

// Where appends a list predicates to the BenefitClaimDelete builder.
func (_d *BenefitClaimDeleteOne) Where(ps ...predicate.BenefitClaim) *BenefitClaimDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BenefitClaimDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{benefitclaim.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitClaimDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
