// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BenefitClaimUpdate is the builder for updating BenefitClaim entities.
type BenefitClaimUpdate struct {
	config
	hooks    []Hook
	mutation *BenefitClaimMutation
}

// Where appends a list predicates to the BenefitClaimUpdate builder.
func (_u *BenefitClaimUpdate) Where(ps ...predicate.BenefitClaim) *BenefitClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitClaimUpdate) SetUpdatedAt(v time.Time) *BenefitClaimUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *BenefitClaimUpdate) SetCampaignID(v int64) *BenefitClaimUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableCampaignID(v *int64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BenefitClaimUpdate) SetUserID(v int64) *BenefitClaimUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableUserID(v *int64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitClaimUpdate) SetStatus(v string) *BenefitClaimUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableStatus(v *string) *BenefitClaimUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (_u *BenefitClaimUpdate) SetEligibleRechargeAmount(v float64) *BenefitClaimUpdate {
	_u.mutation.ResetEligibleRechargeAmount()
	_u.mutation.SetEligibleRechargeAmount(v)
	return _u
}

// SetNillableEligibleRechargeAmount sets the "eligible_recharge_amount" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableEligibleRechargeAmount(v *float64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetEligibleRechargeAmount(*v)
	}
	return _u
}

// AddEligibleRechargeAmount adds value to the "eligible_recharge_amount" field.
func (_u *BenefitClaimUpdate) AddEligibleRechargeAmount(v float64) *BenefitClaimUpdate {
	_u.mutation.AddEligibleRechargeAmount(v)
	return _u
}

// SetGrantedAmount sets the "granted_amount" field.
func (_u *BenefitClaimUpdate) SetGrantedAmount(v float64) *BenefitClaimUpdate {
	_u.mutation.ResetGrantedAmount()
	_u.mutation.SetGrantedAmount(v)
	return _u
}

// SetNillableGrantedAmount sets the "granted_amount" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableGrantedAmount(v *float64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetGrantedAmount(*v)
	}
	return _u
}

// AddGrantedAmount adds value to the "granted_amount" field.
func (_u *BenefitClaimUpdate) AddGrantedAmount(v float64) *BenefitClaimUpdate {
	_u.mutation.AddGrantedAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BenefitClaimUpdate) SetBalanceBefore(v float64) *BenefitClaimUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableBalanceBefore(v *float64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BenefitClaimUpdate) AddBalanceBefore(v float64) *BenefitClaimUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BenefitClaimUpdate) SetBalanceAfter(v float64) *BenefitClaimUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableBalanceAfter(v *float64) *BenefitClaimUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BenefitClaimUpdate) AddBalanceAfter(v float64) *BenefitClaimUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *BenefitClaimUpdate) SetClaimedAt(v time.Time) *BenefitClaimUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableClaimedAt(v *time.Time) *BenefitClaimUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_u *BenefitClaimUpdate) SetSourceRedeemCode(v string) *BenefitClaimUpdate {
	_u.mutation.SetSourceRedeemCode(v)
	return _u
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_u *BenefitClaimUpdate) SetNillableSourceRedeemCode(v *string) *BenefitClaimUpdate {
	if v != nil {
		_u.SetSourceRedeemCode(*v)
	}
	return _u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (_u *BenefitClaimUpdate) ClearSourceRedeemCode() *BenefitClaimUpdate {
	_u.mutation.ClearSourceRedeemCode()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *BenefitClaimUpdate) SetMetadata(v map[string]interface{}) *BenefitClaimUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *BenefitClaimUpdate) ClearMetadata() *BenefitClaimUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCampaign sets the "campaign" edge to the BenefitCampaign entity.
func (_u *BenefitClaimUpdate) SetCampaign(v *BenefitCampaign) *BenefitClaimUpdate {
	return _u.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *BenefitClaimUpdate) SetUser(v *User) *BenefitClaimUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BenefitClaimMutation object of the builder.
func (_u *BenefitClaimUpdate) Mutation() *BenefitClaimMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the BenefitCampaign entity.
func (_u *BenefitClaimUpdate) ClearCampaign() *BenefitClaimUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BenefitClaimUpdate) ClearUser() *BenefitClaimUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BenefitClaimUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BenefitClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitClaimUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitClaimUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRedeemCode(); ok {
		if err := benefitclaim.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.source_redeem_code": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitClaim.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitClaim.user"`)
	}
	return nil
}

func (_u *BenefitClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitclaim.Table, benefitclaim.Columns, sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitclaim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EligibleRechargeAmount(); ok {
		_spec.SetField(benefitclaim.FieldEligibleRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEligibleRechargeAmount(); ok {
		_spec.AddField(benefitclaim.FieldEligibleRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantedAmount(); ok {
		_spec.SetField(benefitclaim.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedAmount(); ok {
		_spec.AddField(benefitclaim.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(benefitclaim.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(benefitclaim.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(benefitclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(benefitclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(benefitclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceRedeemCode(); ok {
		_spec.SetField(benefitclaim.FieldSourceRedeemCode, field.TypeString, value)
	}
	if _u.mutation.SourceRedeemCodeCleared() {
		_spec.ClearField(benefitclaim.FieldSourceRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(benefitclaim.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(benefitclaim.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.CampaignTable,
			Columns: []string{benefitclaim.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.CampaignTable,
			Columns: []string{benefitclaim.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.UserTable,
			Columns: []string{benefitclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.UserTable,
			Columns: []string{benefitclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BenefitClaimUpdateOne is the builder for updating a single BenefitClaim entity.
type BenefitClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BenefitClaimMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BenefitClaimUpdateOne) SetUpdatedAt(v time.Time) *BenefitClaimUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *BenefitClaimUpdateOne) SetCampaignID(v int64) *BenefitClaimUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableCampaignID(v *int64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BenefitClaimUpdateOne) SetUserID(v int64) *BenefitClaimUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableUserID(v *int64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BenefitClaimUpdateOne) SetStatus(v string) *BenefitClaimUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableStatus(v *string) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleRechargeAmount sets the "eligible_recharge_amount" field.
func (_u *BenefitClaimUpdateOne) SetEligibleRechargeAmount(v float64) *BenefitClaimUpdateOne {
	_u.mutation.ResetEligibleRechargeAmount()
	_u.mutation.SetEligibleRechargeAmount(v)
	return _u
}

// SetNillableEligibleRechargeAmount sets the "eligible_recharge_amount" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableEligibleRechargeAmount(v *float64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetEligibleRechargeAmount(*v)
	}
	return _u
}

// AddEligibleRechargeAmount adds value to the "eligible_recharge_amount" field.
func (_u *BenefitClaimUpdateOne) AddEligibleRechargeAmount(v float64) *BenefitClaimUpdateOne {
	_u.mutation.AddEligibleRechargeAmount(v)
	return _u
}

// SetGrantedAmount sets the "granted_amount" field.
func (_u *BenefitClaimUpdateOne) SetGrantedAmount(v float64) *BenefitClaimUpdateOne {
	_u.mutation.ResetGrantedAmount()
	_u.mutation.SetGrantedAmount(v)
	return _u
}

// SetNillableGrantedAmount sets the "granted_amount" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableGrantedAmount(v *float64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetGrantedAmount(*v)
	}
	return _u
}

// AddGrantedAmount adds value to the "granted_amount" field.
func (_u *BenefitClaimUpdateOne) AddGrantedAmount(v float64) *BenefitClaimUpdateOne {
	_u.mutation.AddGrantedAmount(v)
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BenefitClaimUpdateOne) SetBalanceBefore(v float64) *BenefitClaimUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableBalanceBefore(v *float64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BenefitClaimUpdateOne) AddBalanceBefore(v float64) *BenefitClaimUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BenefitClaimUpdateOne) SetBalanceAfter(v float64) *BenefitClaimUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableBalanceAfter(v *float64) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BenefitClaimUpdateOne) AddBalanceAfter(v float64) *BenefitClaimUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *BenefitClaimUpdateOne) SetClaimedAt(v time.Time) *BenefitClaimUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableClaimedAt(v *time.Time) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetSourceRedeemCode sets the "source_redeem_code" field.
func (_u *BenefitClaimUpdateOne) SetSourceRedeemCode(v string) *BenefitClaimUpdateOne {
	_u.mutation.SetSourceRedeemCode(v)
	return _u
}

// SetNillableSourceRedeemCode sets the "source_redeem_code" field if the given value is not nil.
func (_u *BenefitClaimUpdateOne) SetNillableSourceRedeemCode(v *string) *BenefitClaimUpdateOne {
	if v != nil {
		_u.SetSourceRedeemCode(*v)
	}
	return _u
}

// ClearSourceRedeemCode clears the value of the "source_redeem_code" field.
func (_u *BenefitClaimUpdateOne) ClearSourceRedeemCode() *BenefitClaimUpdateOne {
	_u.mutation.ClearSourceRedeemCode()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *BenefitClaimUpdateOne) SetMetadata(v map[string]interface{}) *BenefitClaimUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *BenefitClaimUpdateOne) ClearMetadata() *BenefitClaimUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCampaign sets the "campaign" edge to the BenefitCampaign entity.
func (_u *BenefitClaimUpdateOne) SetCampaign(v *BenefitCampaign) *BenefitClaimUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *BenefitClaimUpdateOne) SetUser(v *User) *BenefitClaimUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BenefitClaimMutation object of the builder.
func (_u *BenefitClaimUpdateOne) Mutation() *BenefitClaimMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the BenefitCampaign entity.
func (_u *BenefitClaimUpdateOne) ClearCampaign() *BenefitClaimUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BenefitClaimUpdateOne) ClearUser() *BenefitClaimUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the BenefitClaimUpdate builder.
func (_u *BenefitClaimUpdateOne) Where(ps ...predicate.BenefitClaim) *BenefitClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BenefitClaimUpdateOne) Select(field string, fields ...string) *BenefitClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BenefitClaim entity.
func (_u *BenefitClaimUpdateOne) Save(ctx context.Context) (*BenefitClaim, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BenefitClaimUpdateOne) SaveX(ctx context.Context) *BenefitClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BenefitClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BenefitClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BenefitClaimUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := benefitclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BenefitClaimUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := benefitclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRedeemCode(); ok {
		if err := benefitclaim.SourceRedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "source_redeem_code", err: fmt.Errorf(`ent: validator failed for field "BenefitClaim.source_redeem_code": %w`, err)}
		}
	}
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitClaim.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BenefitClaim.user"`)
	}
	return nil
}

func (_u *BenefitClaimUpdateOne) sqlSave(ctx context.Context) (_node *BenefitClaim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(benefitclaim.Table, benefitclaim.Columns, sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BenefitClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, benefitclaim.FieldID)
		for _, f := range fields {
			if !benefitclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != benefitclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(benefitclaim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EligibleRechargeAmount(); ok {
		_spec.SetField(benefitclaim.FieldEligibleRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEligibleRechargeAmount(); ok {
		_spec.AddField(benefitclaim.FieldEligibleRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GrantedAmount(); ok {
		_spec.SetField(benefitclaim.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGrantedAmount(); ok {
		_spec.AddField(benefitclaim.FieldGrantedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(benefitclaim.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(benefitclaim.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(benefitclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(benefitclaim.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(benefitclaim.FieldClaimedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceRedeemCode(); ok {
		_spec.SetField(benefitclaim.FieldSourceRedeemCode, field.TypeString, value)
	}
	if _u.mutation.SourceRedeemCodeCleared() {
		_spec.ClearField(benefitclaim.FieldSourceRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(benefitclaim.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(benefitclaim.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.CampaignTable,
			Columns: []string{benefitclaim.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.CampaignTable,
			Columns: []string{benefitclaim.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.UserTable,
			Columns: []string{benefitclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   benefitclaim.UserTable,
			Columns: []string{benefitclaim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BenefitClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{benefitclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
