// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BenefitClaim is the model entity for the BenefitClaim schema.
type BenefitClaim struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EligibleRechargeAmount holds the value of the "eligible_recharge_amount" field.
	EligibleRechargeAmount float64 `json:"eligible_recharge_amount,omitempty"`
	// GrantedAmount holds the value of the "granted_amount" field.
	GrantedAmount float64 `json:"granted_amount,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore float64 `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// ClaimedAt holds the value of the "claimed_at" field.
	ClaimedAt time.Time `json:"claimed_at,omitempty"`
	// SourceRedeemCode holds the value of the "source_redeem_code" field.
	SourceRedeemCode *string `json:"source_redeem_code,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BenefitClaimQuery when eager-loading is set.
	Edges        BenefitClaimEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BenefitClaimEdges holds the relations/edges for other nodes in the graph.
type BenefitClaimEdges struct {
	// Campaign holds the value of the campaign edge.
	Campaign *BenefitCampaign `json:"campaign,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CampaignOrErr returns the Campaign value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BenefitClaimEdges) CampaignOrErr() (*BenefitCampaign, error) {
	if e.Campaign != nil {
		return e.Campaign, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: benefitcampaign.Label}
	}
	return nil, &NotLoadedError{edge: "campaign"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BenefitClaimEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BenefitClaim) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case benefitclaim.FieldMetadata:
			values[i] = new([]byte)
		case benefitclaim.FieldEligibleRechargeAmount, benefitclaim.FieldGrantedAmount, benefitclaim.FieldBalanceBefore, benefitclaim.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case benefitclaim.FieldID, benefitclaim.FieldCampaignID, benefitclaim.FieldUserID:
			values[i] = new(sql.NullInt64)
		case benefitclaim.FieldStatus, benefitclaim.FieldSourceRedeemCode:
			values[i] = new(sql.NullString)
		case benefitclaim.FieldCreatedAt, benefitclaim.FieldUpdatedAt, benefitclaim.FieldClaimedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BenefitClaim fields.
func (_m *BenefitClaim) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case benefitclaim.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case benefitclaim.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case benefitclaim.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case benefitclaim.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case benefitclaim.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case benefitclaim.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case benefitclaim.FieldEligibleRechargeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field eligible_recharge_amount", values[i])
			} else if value.Valid {
				_m.EligibleRechargeAmount = value.Float64
			}
		case benefitclaim.FieldGrantedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field granted_amount", values[i])
			} else if value.Valid {
				_m.GrantedAmount = value.Float64
			}
		case benefitclaim.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Float64
			}
		case benefitclaim.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case benefitclaim.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = value.Time
			}
		case benefitclaim.FieldSourceRedeemCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_redeem_code", values[i])
			} else if value.Valid {
				_m.SourceRedeemCode = new(string)
				*_m.SourceRedeemCode = value.String
			}
		case benefitclaim.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BenefitClaim.
// This includes values selected through modifiers, order, etc.
func (_m *BenefitClaim) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCampaign queries the "campaign" edge of the BenefitClaim entity.
func (_m *BenefitClaim) QueryCampaign() *BenefitCampaignQuery {
	return NewBenefitClaimClient(_m.config).QueryCampaign(_m)
}

// QueryUser queries the "user" edge of the BenefitClaim entity.
func (_m *BenefitClaim) QueryUser() *UserQuery {
	return NewBenefitClaimClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this BenefitClaim.
// Note that you need to call BenefitClaim.Unwrap() before calling this method if this BenefitClaim
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BenefitClaim) Update() *BenefitClaimUpdateOne {
	return NewBenefitClaimClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BenefitClaim entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BenefitClaim) Unwrap() *BenefitClaim {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BenefitClaim is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BenefitClaim) String() string {
	var builder strings.Builder
	builder.WriteString("BenefitClaim(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("eligible_recharge_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.EligibleRechargeAmount))
	builder.WriteString(", ")
	builder.WriteString("granted_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantedAmount))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("claimed_at=")
	builder.WriteString(_m.ClaimedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SourceRedeemCode; v != nil {
		builder.WriteString("source_redeem_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// BenefitClaims is a parsable slice of BenefitClaim.
type BenefitClaims []*BenefitClaim
