// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
)

// BenefitCampaign is the model entity for the BenefitCampaign schema.
type BenefitCampaign struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Visible holds the value of the "visible" field.
	Visible bool `json:"visible,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// ThresholdAmount holds the value of the "threshold_amount" field.
	ThresholdAmount float64 `json:"threshold_amount,omitempty"`
	// GrantAmount holds the value of the "grant_amount" field.
	GrantAmount float64 `json:"grant_amount,omitempty"`
	// RechargeScope holds the value of the "recharge_scope" field.
	RechargeScope string `json:"recharge_scope,omitempty"`
	// Copy holds the value of the "copy" field.
	Copy map[string]string `json:"copy,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BenefitCampaignQuery when eager-loading is set.
	Edges        BenefitCampaignEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BenefitCampaignEdges holds the relations/edges for other nodes in the graph.
type BenefitCampaignEdges struct {
	// Claims holds the value of the claims edge.
	Claims []*BenefitClaim `json:"claims,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClaimsOrErr returns the Claims value or an error if the edge
// was not loaded in eager-loading.
func (e BenefitCampaignEdges) ClaimsOrErr() ([]*BenefitClaim, error) {
	if e.loadedTypes[0] {
		return e.Claims, nil
	}
	return nil, &NotLoadedError{edge: "claims"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BenefitCampaign) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case benefitcampaign.FieldCopy:
			values[i] = new([]byte)
		case benefitcampaign.FieldEnabled, benefitcampaign.FieldVisible:
			values[i] = new(sql.NullBool)
		case benefitcampaign.FieldThresholdAmount, benefitcampaign.FieldGrantAmount:
			values[i] = new(sql.NullFloat64)
		case benefitcampaign.FieldID, benefitcampaign.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case benefitcampaign.FieldName, benefitcampaign.FieldRechargeScope:
			values[i] = new(sql.NullString)
		case benefitcampaign.FieldCreatedAt, benefitcampaign.FieldUpdatedAt, benefitcampaign.FieldDeletedAt, benefitcampaign.FieldStartsAt, benefitcampaign.FieldEndsAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BenefitCampaign fields.
func (_m *BenefitCampaign) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case benefitcampaign.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case benefitcampaign.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case benefitcampaign.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case benefitcampaign.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case benefitcampaign.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case benefitcampaign.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case benefitcampaign.FieldVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field visible", values[i])
			} else if value.Valid {
				_m.Visible = value.Bool
			}
		case benefitcampaign.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case benefitcampaign.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case benefitcampaign.FieldThresholdAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold_amount", values[i])
			} else if value.Valid {
				_m.ThresholdAmount = value.Float64
			}
		case benefitcampaign.FieldGrantAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_amount", values[i])
			} else if value.Valid {
				_m.GrantAmount = value.Float64
			}
		case benefitcampaign.FieldRechargeScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_scope", values[i])
			} else if value.Valid {
				_m.RechargeScope = value.String
			}
		case benefitcampaign.FieldCopy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field copy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Copy); err != nil {
					return fmt.Errorf("unmarshal field copy: %w", err)
				}
			}
		case benefitcampaign.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BenefitCampaign.
// This includes values selected through modifiers, order, etc.
func (_m *BenefitCampaign) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClaims queries the "claims" edge of the BenefitCampaign entity.
func (_m *BenefitCampaign) QueryClaims() *BenefitClaimQuery {
	return NewBenefitCampaignClient(_m.config).QueryClaims(_m)
}

// Update returns a builder for updating this BenefitCampaign.
// Note that you need to call BenefitCampaign.Unwrap() before calling this method if this BenefitCampaign
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BenefitCampaign) Update() *BenefitCampaignUpdateOne {
	return NewBenefitCampaignClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BenefitCampaign entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BenefitCampaign) Unwrap() *BenefitCampaign {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BenefitCampaign is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BenefitCampaign) String() string {
	var builder strings.Builder
	builder.WriteString("BenefitCampaign(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visible))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("threshold_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThresholdAmount))
	builder.WriteString(", ")
	builder.WriteString("grant_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantAmount))
	builder.WriteString(", ")
	builder.WriteString("recharge_scope=")
	builder.WriteString(_m.RechargeScope)
	builder.WriteString(", ")
	builder.WriteString("copy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Copy))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// BenefitCampaigns is a parsable slice of BenefitCampaign.
type BenefitCampaigns []*BenefitCampaign
