// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BenefitCampaignDelete is the builder for deleting a BenefitCampaign entity.
type BenefitCampaignDelete struct {
	config
	hooks    []Hook
	mutation *BenefitCampaignMutation
}

// Where appends a list predicates to the BenefitCampaignDelete builder.
func (_d *BenefitCampaignDelete) Where(ps ...predicate.BenefitCampaign) *BenefitCampaignDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BenefitCampaignDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitCampaignDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BenefitCampaignDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(benefitcampaign.Table, sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BenefitCampaignDeleteOne is the builder for deleting a single BenefitCampaign entity.
type BenefitCampaignDeleteOne struct {
	_d *BenefitCampaignDelete
}

// Where appends a list predicates to the BenefitCampaignDelete builder.
func (_d *BenefitCampaignDeleteOne) Where(ps ...predicate.BenefitCampaign) *BenefitCampaignDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BenefitCampaignDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{benefitcampaign.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BenefitCampaignDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
