// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/benefitcampaign"
	"github.com/Wei-Shaw/sub2api/ent/benefitclaim"
)

// BenefitCampaignCreate is the builder for creating a BenefitCampaign entity.
type BenefitCampaignCreate struct {
	config
	mutation *BenefitCampaignMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BenefitCampaignCreate) SetCreatedAt(v time.Time) *BenefitCampaignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableCreatedAt(v *time.Time) *BenefitCampaignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BenefitCampaignCreate) SetUpdatedAt(v time.Time) *BenefitCampaignCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableUpdatedAt(v *time.Time) *BenefitCampaignCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BenefitCampaignCreate) SetDeletedAt(v time.Time) *BenefitCampaignCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableDeletedAt(v *time.Time) *BenefitCampaignCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BenefitCampaignCreate) SetName(v string) *BenefitCampaignCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BenefitCampaignCreate) SetEnabled(v bool) *BenefitCampaignCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableEnabled(v *bool) *BenefitCampaignCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetVisible sets the "visible" field.
func (_c *BenefitCampaignCreate) SetVisible(v bool) *BenefitCampaignCreate {
	_c.mutation.SetVisible(v)
	return _c
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableVisible(v *bool) *BenefitCampaignCreate {
	if v != nil {
		_c.SetVisible(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *BenefitCampaignCreate) SetStartsAt(v time.Time) *BenefitCampaignCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *BenefitCampaignCreate) SetEndsAt(v time.Time) *BenefitCampaignCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetThresholdAmount sets the "threshold_amount" field.
func (_c *BenefitCampaignCreate) SetThresholdAmount(v float64) *BenefitCampaignCreate {
	_c.mutation.SetThresholdAmount(v)
	return _c
}

// SetGrantAmount sets the "grant_amount" field.
func (_c *BenefitCampaignCreate) SetGrantAmount(v float64) *BenefitCampaignCreate {
	_c.mutation.SetGrantAmount(v)
	return _c
}

// SetRechargeScope sets the "recharge_scope" field.
func (_c *BenefitCampaignCreate) SetRechargeScope(v string) *BenefitCampaignCreate {
	_c.mutation.SetRechargeScope(v)
	return _c
}

// SetNillableRechargeScope sets the "recharge_scope" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableRechargeScope(v *string) *BenefitCampaignCreate {
	if v != nil {
		_c.SetRechargeScope(*v)
	}
	return _c
}

// SetCopy sets the "copy" field.
func (_c *BenefitCampaignCreate) SetCopy(v map[string]string) *BenefitCampaignCreate {
	_c.mutation.SetCopy(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *BenefitCampaignCreate) SetSortOrder(v int) *BenefitCampaignCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *BenefitCampaignCreate) SetNillableSortOrder(v *int) *BenefitCampaignCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddClaimIDs adds the "claims" edge to the BenefitClaim entity by IDs.
func (_c *BenefitCampaignCreate) AddClaimIDs(ids ...int64) *BenefitCampaignCreate {
	_c.mutation.AddClaimIDs(ids...)
	return _c
}

// AddClaims adds the "claims" edges to the BenefitClaim entity.
func (_c *BenefitCampaignCreate) AddClaims(v ...*BenefitClaim) *BenefitCampaignCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddClaimIDs(ids...)
}

// Mutation returns the BenefitCampaignMutation object of the builder.
func (_c *BenefitCampaignCreate) Mutation() *BenefitCampaignMutation {
	return _c.mutation
}

// Save creates the BenefitCampaign in the database.
func (_c *BenefitCampaignCreate) Save(ctx context.Context) (*BenefitCampaign, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BenefitCampaignCreate) SaveX(ctx context.Context) *BenefitCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitCampaignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitCampaignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BenefitCampaignCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if benefitcampaign.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized benefitcampaign.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := benefitcampaign.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if benefitcampaign.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized benefitcampaign.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := benefitcampaign.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := benefitcampaign.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Visible(); !ok {
		v := benefitcampaign.DefaultVisible
		_c.mutation.SetVisible(v)
	}
	if _, ok := _c.mutation.RechargeScope(); !ok {
		v := benefitcampaign.DefaultRechargeScope
		_c.mutation.SetRechargeScope(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := benefitcampaign.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BenefitCampaignCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BenefitCampaign.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BenefitCampaign.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BenefitCampaign.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := benefitcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "BenefitCampaign.enabled"`)}
	}
	if _, ok := _c.mutation.Visible(); !ok {
		return &ValidationError{Name: "visible", err: errors.New(`ent: missing required field "BenefitCampaign.visible"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "BenefitCampaign.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "BenefitCampaign.ends_at"`)}
	}
	if _, ok := _c.mutation.ThresholdAmount(); !ok {
		return &ValidationError{Name: "threshold_amount", err: errors.New(`ent: missing required field "BenefitCampaign.threshold_amount"`)}
	}
	if _, ok := _c.mutation.GrantAmount(); !ok {
		return &ValidationError{Name: "grant_amount", err: errors.New(`ent: missing required field "BenefitCampaign.grant_amount"`)}
	}
	if _, ok := _c.mutation.RechargeScope(); !ok {
		return &ValidationError{Name: "recharge_scope", err: errors.New(`ent: missing required field "BenefitCampaign.recharge_scope"`)}
	}
	if v, ok := _c.mutation.RechargeScope(); ok {
		if err := benefitcampaign.RechargeScopeValidator(v); err != nil {
			return &ValidationError{Name: "recharge_scope", err: fmt.Errorf(`ent: validator failed for field "BenefitCampaign.recharge_scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BenefitCampaign.sort_order"`)}
	}
	return nil
}

func (_c *BenefitCampaignCreate) sqlSave(ctx context.Context) (*BenefitCampaign, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BenefitCampaignCreate) createSpec() (*BenefitCampaign, *sqlgraph.CreateSpec) {
	var (
		_node = &BenefitCampaign{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(benefitcampaign.Table, sqlgraph.NewFieldSpec(benefitcampaign.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(benefitcampaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(benefitcampaign.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(benefitcampaign.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(benefitcampaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(benefitcampaign.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Visible(); ok {
		_spec.SetField(benefitcampaign.FieldVisible, field.TypeBool, value)
		_node.Visible = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(benefitcampaign.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(benefitcampaign.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.ThresholdAmount(); ok {
		_spec.SetField(benefitcampaign.FieldThresholdAmount, field.TypeFloat64, value)
		_node.ThresholdAmount = value
	}
	if value, ok := _c.mutation.GrantAmount(); ok {
		_spec.SetField(benefitcampaign.FieldGrantAmount, field.TypeFloat64, value)
		_node.GrantAmount = value
	}
	if value, ok := _c.mutation.RechargeScope(); ok {
		_spec.SetField(benefitcampaign.FieldRechargeScope, field.TypeString, value)
		_node.RechargeScope = value
	}
	if value, ok := _c.mutation.Copy(); ok {
		_spec.SetField(benefitcampaign.FieldCopy, field.TypeJSON, value)
		_node.Copy = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(benefitcampaign.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.ClaimsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   benefitcampaign.ClaimsTable,
			Columns: []string{benefitcampaign.ClaimsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(benefitclaim.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BenefitCampaign.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BenefitCampaignUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BenefitCampaignCreate) OnConflict(opts ...sql.ConflictOption) *BenefitCampaignUpsertOne {
	_c.conflict = opts
	return &BenefitCampaignUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BenefitCampaignCreate) OnConflictColumns(columns ...string) *BenefitCampaignUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BenefitCampaignUpsertOne{
		create: _c,
	}
}

type (
	// BenefitCampaignUpsertOne is the builder for "upsert"-ing
	//  one BenefitCampaign node.
	BenefitCampaignUpsertOne struct {
		create *BenefitCampaignCreate
	}

	// BenefitCampaignUpsert is the "OnConflict" setter.
	BenefitCampaignUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitCampaignUpsert) SetUpdatedAt(v time.Time) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateUpdatedAt() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BenefitCampaignUpsert) SetDeletedAt(v time.Time) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateDeletedAt() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BenefitCampaignUpsert) ClearDeletedAt() *BenefitCampaignUpsert {
	u.SetNull(benefitcampaign.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *BenefitCampaignUpsert) SetName(v string) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateName() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *BenefitCampaignUpsert) SetEnabled(v bool) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateEnabled() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldEnabled)
	return u
}

// SetVisible sets the "visible" field.
func (u *BenefitCampaignUpsert) SetVisible(v bool) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldVisible, v)
	return u
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateVisible() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldVisible)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *BenefitCampaignUpsert) SetStartsAt(v time.Time) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateStartsAt() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *BenefitCampaignUpsert) SetEndsAt(v time.Time) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateEndsAt() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldEndsAt)
	return u
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *BenefitCampaignUpsert) SetThresholdAmount(v float64) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldThresholdAmount, v)
	return u
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateThresholdAmount() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldThresholdAmount)
	return u
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *BenefitCampaignUpsert) AddThresholdAmount(v float64) *BenefitCampaignUpsert {
	u.Add(benefitcampaign.FieldThresholdAmount, v)
	return u
}

// SetGrantAmount sets the "grant_amount" field.
func (u *BenefitCampaignUpsert) SetGrantAmount(v float64) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldGrantAmount, v)
	return u
}

// UpdateGrantAmount sets the "grant_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateGrantAmount() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldGrantAmount)
	return u
}

// AddGrantAmount adds v to the "grant_amount" field.
func (u *BenefitCampaignUpsert) AddGrantAmount(v float64) *BenefitCampaignUpsert {
	u.Add(benefitcampaign.FieldGrantAmount, v)
	return u
}

// SetRechargeScope sets the "recharge_scope" field.
func (u *BenefitCampaignUpsert) SetRechargeScope(v string) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldRechargeScope, v)
	return u
}

// UpdateRechargeScope sets the "recharge_scope" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateRechargeScope() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldRechargeScope)
	return u
}

// SetCopy sets the "copy" field.
func (u *BenefitCampaignUpsert) SetCopy(v map[string]string) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldCopy, v)
	return u
}

// UpdateCopy sets the "copy" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateCopy() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldCopy)
	return u
}

// ClearCopy clears the value of the "copy" field.
func (u *BenefitCampaignUpsert) ClearCopy() *BenefitCampaignUpsert {
	u.SetNull(benefitcampaign.FieldCopy)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *BenefitCampaignUpsert) SetSortOrder(v int) *BenefitCampaignUpsert {
	u.Set(benefitcampaign.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BenefitCampaignUpsert) UpdateSortOrder() *BenefitCampaignUpsert {
	u.SetExcluded(benefitcampaign.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BenefitCampaignUpsert) AddSortOrder(v int) *BenefitCampaignUpsert {
	u.Add(benefitcampaign.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BenefitCampaignUpsertOne) UpdateNewValues() *BenefitCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(benefitcampaign.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BenefitCampaignUpsertOne) Ignore() *BenefitCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BenefitCampaignUpsertOne) DoNothing() *BenefitCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BenefitCampaignCreate.OnConflict
// documentation for more info.
func (u *BenefitCampaignUpsertOne) Update(set func(*BenefitCampaignUpsert)) *BenefitCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BenefitCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitCampaignUpsertOne) SetUpdatedAt(v time.Time) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateUpdatedAt() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BenefitCampaignUpsertOne) SetDeletedAt(v time.Time) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateDeletedAt() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BenefitCampaignUpsertOne) ClearDeletedAt() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *BenefitCampaignUpsertOne) SetName(v string) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateName() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BenefitCampaignUpsertOne) SetEnabled(v bool) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateEnabled() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateEnabled()
	})
}

// SetVisible sets the "visible" field.
func (u *BenefitCampaignUpsertOne) SetVisible(v bool) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateVisible() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateVisible()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *BenefitCampaignUpsertOne) SetStartsAt(v time.Time) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateStartsAt() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *BenefitCampaignUpsertOne) SetEndsAt(v time.Time) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateEndsAt() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateEndsAt()
	})
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *BenefitCampaignUpsertOne) SetThresholdAmount(v float64) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetThresholdAmount(v)
	})
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *BenefitCampaignUpsertOne) AddThresholdAmount(v float64) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddThresholdAmount(v)
	})
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateThresholdAmount() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateThresholdAmount()
	})
}

// SetGrantAmount sets the "grant_amount" field.
func (u *BenefitCampaignUpsertOne) SetGrantAmount(v float64) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetGrantAmount(v)
	})
}

// AddGrantAmount adds v to the "grant_amount" field.
func (u *BenefitCampaignUpsertOne) AddGrantAmount(v float64) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddGrantAmount(v)
	})
}

// UpdateGrantAmount sets the "grant_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateGrantAmount() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateGrantAmount()
	})
}

// SetRechargeScope sets the "recharge_scope" field.
func (u *BenefitCampaignUpsertOne) SetRechargeScope(v string) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetRechargeScope(v)
	})
}

// UpdateRechargeScope sets the "recharge_scope" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateRechargeScope() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateRechargeScope()
	})
}

// SetCopy sets the "copy" field.
func (u *BenefitCampaignUpsertOne) SetCopy(v map[string]string) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetCopy(v)
	})
}

// UpdateCopy sets the "copy" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateCopy() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateCopy()
	})
}

// ClearCopy clears the value of the "copy" field.
func (u *BenefitCampaignUpsertOne) ClearCopy() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.ClearCopy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BenefitCampaignUpsertOne) SetSortOrder(v int) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BenefitCampaignUpsertOne) AddSortOrder(v int) *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BenefitCampaignUpsertOne) UpdateSortOrder() *BenefitCampaignUpsertOne {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *BenefitCampaignUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BenefitCampaignCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BenefitCampaignUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BenefitCampaignUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BenefitCampaignUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BenefitCampaignCreateBulk is the builder for creating many BenefitCampaign entities in bulk.
type BenefitCampaignCreateBulk struct {
	config
	err      error
	builders []*BenefitCampaignCreate
	conflict []sql.ConflictOption
}

// Save creates the BenefitCampaign entities in the database.
func (_c *BenefitCampaignCreateBulk) Save(ctx context.Context) ([]*BenefitCampaign, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BenefitCampaign, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BenefitCampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BenefitCampaignCreateBulk) SaveX(ctx context.Context) []*BenefitCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BenefitCampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BenefitCampaignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BenefitCampaign.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BenefitCampaignUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BenefitCampaignCreateBulk) OnConflict(opts ...sql.ConflictOption) *BenefitCampaignUpsertBulk {
	_c.conflict = opts
	return &BenefitCampaignUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BenefitCampaignCreateBulk) OnConflictColumns(columns ...string) *BenefitCampaignUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BenefitCampaignUpsertBulk{
		create: _c,
	}
}

// BenefitCampaignUpsertBulk is the builder for "upsert"-ing
// a bulk of BenefitCampaign nodes.
type BenefitCampaignUpsertBulk struct {
	create *BenefitCampaignCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BenefitCampaignUpsertBulk) UpdateNewValues() *BenefitCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(benefitcampaign.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BenefitCampaign.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BenefitCampaignUpsertBulk) Ignore() *BenefitCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BenefitCampaignUpsertBulk) DoNothing() *BenefitCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BenefitCampaignCreateBulk.OnConflict
// documentation for more info.
func (u *BenefitCampaignUpsertBulk) Update(set func(*BenefitCampaignUpsert)) *BenefitCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BenefitCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BenefitCampaignUpsertBulk) SetUpdatedAt(v time.Time) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateUpdatedAt() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *BenefitCampaignUpsertBulk) SetDeletedAt(v time.Time) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateDeletedAt() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *BenefitCampaignUpsertBulk) ClearDeletedAt() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *BenefitCampaignUpsertBulk) SetName(v string) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateName() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *BenefitCampaignUpsertBulk) SetEnabled(v bool) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateEnabled() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateEnabled()
	})
}

// SetVisible sets the "visible" field.
func (u *BenefitCampaignUpsertBulk) SetVisible(v bool) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetVisible(v)
	})
}

// UpdateVisible sets the "visible" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateVisible() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateVisible()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *BenefitCampaignUpsertBulk) SetStartsAt(v time.Time) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateStartsAt() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *BenefitCampaignUpsertBulk) SetEndsAt(v time.Time) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateEndsAt() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateEndsAt()
	})
}

// SetThresholdAmount sets the "threshold_amount" field.
func (u *BenefitCampaignUpsertBulk) SetThresholdAmount(v float64) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetThresholdAmount(v)
	})
}

// AddThresholdAmount adds v to the "threshold_amount" field.
func (u *BenefitCampaignUpsertBulk) AddThresholdAmount(v float64) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddThresholdAmount(v)
	})
}

// UpdateThresholdAmount sets the "threshold_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateThresholdAmount() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateThresholdAmount()
	})
}

// SetGrantAmount sets the "grant_amount" field.
func (u *BenefitCampaignUpsertBulk) SetGrantAmount(v float64) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetGrantAmount(v)
	})
}

// AddGrantAmount adds v to the "grant_amount" field.
func (u *BenefitCampaignUpsertBulk) AddGrantAmount(v float64) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddGrantAmount(v)
	})
}

// UpdateGrantAmount sets the "grant_amount" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateGrantAmount() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateGrantAmount()
	})
}

// SetRechargeScope sets the "recharge_scope" field.
func (u *BenefitCampaignUpsertBulk) SetRechargeScope(v string) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetRechargeScope(v)
	})
}

// UpdateRechargeScope sets the "recharge_scope" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateRechargeScope() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateRechargeScope()
	})
}

// SetCopy sets the "copy" field.
func (u *BenefitCampaignUpsertBulk) SetCopy(v map[string]string) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetCopy(v)
	})
}

// UpdateCopy sets the "copy" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateCopy() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateCopy()
	})
}

// ClearCopy clears the value of the "copy" field.
func (u *BenefitCampaignUpsertBulk) ClearCopy() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.ClearCopy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BenefitCampaignUpsertBulk) SetSortOrder(v int) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BenefitCampaignUpsertBulk) AddSortOrder(v int) *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BenefitCampaignUpsertBulk) UpdateSortOrder() *BenefitCampaignUpsertBulk {
	return u.Update(func(s *BenefitCampaignUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *BenefitCampaignUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BenefitCampaignCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BenefitCampaignCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BenefitCampaignUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
