// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagestudiotemplate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageStudioTemplateUpdate is the builder for updating ImageStudioTemplate entities.
type ImageStudioTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *ImageStudioTemplateMutation
}

// Where appends a list predicates to the ImageStudioTemplateUpdate builder.
func (_u *ImageStudioTemplateUpdate) Where(ps ...predicate.ImageStudioTemplate) *ImageStudioTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageStudioTemplateUpdate) SetUpdatedAt(v time.Time) *ImageStudioTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *ImageStudioTemplateUpdate) SetKey(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableKey(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ImageStudioTemplateUpdate) SetMode(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableMode(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageStudioTemplateUpdate) SetTitle(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableTitle(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageStudioTemplateUpdate) SetModel(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableModel(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ImageStudioTemplateUpdate) SetImage(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableImage(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetOriginalImageURL sets the "original_image_url" field.
func (_u *ImageStudioTemplateUpdate) SetOriginalImageURL(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetOriginalImageURL(v)
	return _u
}

// SetNillableOriginalImageURL sets the "original_image_url" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableOriginalImageURL(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetOriginalImageURL(*v)
	}
	return _u
}

// ClearOriginalImageURL clears the value of the "original_image_url" field.
func (_u *ImageStudioTemplateUpdate) ClearOriginalImageURL() *ImageStudioTemplateUpdate {
	_u.mutation.ClearOriginalImageURL()
	return _u
}

// SetImageHash sets the "image_hash" field.
func (_u *ImageStudioTemplateUpdate) SetImageHash(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetImageHash(v)
	return _u
}

// SetNillableImageHash sets the "image_hash" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableImageHash(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetImageHash(*v)
	}
	return _u
}

// ClearImageHash clears the value of the "image_hash" field.
func (_u *ImageStudioTemplateUpdate) ClearImageHash() *ImageStudioTemplateUpdate {
	_u.mutation.ClearImageHash()
	return _u
}

// SetImageDownloadError sets the "image_download_error" field.
func (_u *ImageStudioTemplateUpdate) SetImageDownloadError(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetImageDownloadError(v)
	return _u
}

// SetNillableImageDownloadError sets the "image_download_error" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableImageDownloadError(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetImageDownloadError(*v)
	}
	return _u
}

// ClearImageDownloadError clears the value of the "image_download_error" field.
func (_u *ImageStudioTemplateUpdate) ClearImageDownloadError() *ImageStudioTemplateUpdate {
	_u.mutation.ClearImageDownloadError()
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *ImageStudioTemplateUpdate) SetPromptHash(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillablePromptHash(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *ImageStudioTemplateUpdate) ClearPromptHash() *ImageStudioTemplateUpdate {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageStudioTemplateUpdate) SetPrompt(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillablePrompt(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ImageStudioTemplateUpdate) SetSourceName(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableSourceName(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ImageStudioTemplateUpdate) ClearSourceName() *ImageStudioTemplateUpdate {
	_u.mutation.ClearSourceName()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *ImageStudioTemplateUpdate) SetSourceURL(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableSourceURL(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *ImageStudioTemplateUpdate) ClearSourceURL() *ImageStudioTemplateUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ImageStudioTemplateUpdate) SetSourceType(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableSourceType(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// ClearSourceType clears the value of the "source_type" field.
func (_u *ImageStudioTemplateUpdate) ClearSourceType() *ImageStudioTemplateUpdate {
	_u.mutation.ClearSourceType()
	return _u
}

// SetLicense sets the "license" field.
func (_u *ImageStudioTemplateUpdate) SetLicense(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableLicense(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// ClearLicense clears the value of the "license" field.
func (_u *ImageStudioTemplateUpdate) ClearLicense() *ImageStudioTemplateUpdate {
	_u.mutation.ClearLicense()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ImageStudioTemplateUpdate) SetAuthor(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableAuthor(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *ImageStudioTemplateUpdate) ClearAuthor() *ImageStudioTemplateUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *ImageStudioTemplateUpdate) SetMeta(v string) *ImageStudioTemplateUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// SetNillableMeta sets the "meta" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableMeta(v *string) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetMeta(*v)
	}
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *ImageStudioTemplateUpdate) ClearMeta() *ImageStudioTemplateUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ImageStudioTemplateUpdate) SetTags(v []string) *ImageStudioTemplateUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ImageStudioTemplateUpdate) AppendTags(v []string) *ImageStudioTemplateUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ImageStudioTemplateUpdate) ClearTags() *ImageStudioTemplateUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetRequiresReference sets the "requires_reference" field.
func (_u *ImageStudioTemplateUpdate) SetRequiresReference(v bool) *ImageStudioTemplateUpdate {
	_u.mutation.SetRequiresReference(v)
	return _u
}

// SetNillableRequiresReference sets the "requires_reference" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableRequiresReference(v *bool) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetRequiresReference(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImageStudioTemplateUpdate) SetEnabled(v bool) *ImageStudioTemplateUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableEnabled(v *bool) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ImageStudioTemplateUpdate) SetSortOrder(v int) *ImageStudioTemplateUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdate) SetNillableSortOrder(v *int) *ImageStudioTemplateUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ImageStudioTemplateUpdate) AddSortOrder(v int) *ImageStudioTemplateUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// Mutation returns the ImageStudioTemplateMutation object of the builder.
func (_u *ImageStudioTemplateUpdate) Mutation() *ImageStudioTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageStudioTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageStudioTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageStudioTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageStudioTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageStudioTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagestudiotemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageStudioTemplateUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := imagestudiotemplate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := imagestudiotemplate.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := imagestudiotemplate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagestudiotemplate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Image(); ok {
		if err := imagestudiotemplate.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalImageURL(); ok {
		if err := imagestudiotemplate.OriginalImageURLValidator(v); err != nil {
			return &ValidationError{Name: "original_image_url", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.original_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageHash(); ok {
		if err := imagestudiotemplate.ImageHashValidator(v); err != nil {
			return &ValidationError{Name: "image_hash", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageDownloadError(); ok {
		if err := imagestudiotemplate.ImageDownloadErrorValidator(v); err != nil {
			return &ValidationError{Name: "image_download_error", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image_download_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := imagestudiotemplate.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := imagestudiotemplate.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceName(); ok {
		if err := imagestudiotemplate.SourceNameValidator(v); err != nil {
			return &ValidationError{Name: "source_name", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURL(); ok {
		if err := imagestudiotemplate.SourceURLValidator(v); err != nil {
			return &ValidationError{Name: "source_url", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := imagestudiotemplate.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.License(); ok {
		if err := imagestudiotemplate.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.license": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := imagestudiotemplate.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Meta(); ok {
		if err := imagestudiotemplate.MetaValidator(v); err != nil {
			return &ValidationError{Name: "meta", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.meta": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageStudioTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagestudiotemplate.Table, imagestudiotemplate.Columns, sqlgraph.NewFieldSpec(imagestudiotemplate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagestudiotemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(imagestudiotemplate.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(imagestudiotemplate.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imagestudiotemplate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagestudiotemplate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(imagestudiotemplate.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalImageURL(); ok {
		_spec.SetField(imagestudiotemplate.FieldOriginalImageURL, field.TypeString, value)
	}
	if _u.mutation.OriginalImageURLCleared() {
		_spec.ClearField(imagestudiotemplate.FieldOriginalImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.ImageHash(); ok {
		_spec.SetField(imagestudiotemplate.FieldImageHash, field.TypeString, value)
	}
	if _u.mutation.ImageHashCleared() {
		_spec.ClearField(imagestudiotemplate.FieldImageHash, field.TypeString)
	}
	if value, ok := _u.mutation.ImageDownloadError(); ok {
		_spec.SetField(imagestudiotemplate.FieldImageDownloadError, field.TypeString, value)
	}
	if _u.mutation.ImageDownloadErrorCleared() {
		_spec.ClearField(imagestudiotemplate.FieldImageDownloadError, field.TypeString)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(imagestudiotemplate.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(imagestudiotemplate.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagestudiotemplate.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceType, field.TypeString, value)
	}
	if _u.mutation.SourceTypeCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceType, field.TypeString)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(imagestudiotemplate.FieldLicense, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		_spec.ClearField(imagestudiotemplate.FieldLicense, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(imagestudiotemplate.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(imagestudiotemplate.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(imagestudiotemplate.FieldMeta, field.TypeString, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(imagestudiotemplate.FieldMeta, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(imagestudiotemplate.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, imagestudiotemplate.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(imagestudiotemplate.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiresReference(); ok {
		_spec.SetField(imagestudiotemplate.FieldRequiresReference, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(imagestudiotemplate.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(imagestudiotemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(imagestudiotemplate.FieldSortOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagestudiotemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageStudioTemplateUpdateOne is the builder for updating a single ImageStudioTemplate entity.
type ImageStudioTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageStudioTemplateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageStudioTemplateUpdateOne) SetUpdatedAt(v time.Time) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *ImageStudioTemplateUpdateOne) SetKey(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableKey(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *ImageStudioTemplateUpdateOne) SetMode(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableMode(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageStudioTemplateUpdateOne) SetTitle(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableTitle(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageStudioTemplateUpdateOne) SetModel(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableModel(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ImageStudioTemplateUpdateOne) SetImage(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableImage(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetOriginalImageURL sets the "original_image_url" field.
func (_u *ImageStudioTemplateUpdateOne) SetOriginalImageURL(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetOriginalImageURL(v)
	return _u
}

// SetNillableOriginalImageURL sets the "original_image_url" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableOriginalImageURL(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetOriginalImageURL(*v)
	}
	return _u
}

// ClearOriginalImageURL clears the value of the "original_image_url" field.
func (_u *ImageStudioTemplateUpdateOne) ClearOriginalImageURL() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearOriginalImageURL()
	return _u
}

// SetImageHash sets the "image_hash" field.
func (_u *ImageStudioTemplateUpdateOne) SetImageHash(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetImageHash(v)
	return _u
}

// SetNillableImageHash sets the "image_hash" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableImageHash(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetImageHash(*v)
	}
	return _u
}

// ClearImageHash clears the value of the "image_hash" field.
func (_u *ImageStudioTemplateUpdateOne) ClearImageHash() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearImageHash()
	return _u
}

// SetImageDownloadError sets the "image_download_error" field.
func (_u *ImageStudioTemplateUpdateOne) SetImageDownloadError(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetImageDownloadError(v)
	return _u
}

// SetNillableImageDownloadError sets the "image_download_error" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableImageDownloadError(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetImageDownloadError(*v)
	}
	return _u
}

// ClearImageDownloadError clears the value of the "image_download_error" field.
func (_u *ImageStudioTemplateUpdateOne) ClearImageDownloadError() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearImageDownloadError()
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *ImageStudioTemplateUpdateOne) SetPromptHash(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillablePromptHash(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// ClearPromptHash clears the value of the "prompt_hash" field.
func (_u *ImageStudioTemplateUpdateOne) ClearPromptHash() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearPromptHash()
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageStudioTemplateUpdateOne) SetPrompt(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillablePrompt(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ImageStudioTemplateUpdateOne) SetSourceName(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableSourceName(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ImageStudioTemplateUpdateOne) ClearSourceName() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearSourceName()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *ImageStudioTemplateUpdateOne) SetSourceURL(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableSourceURL(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *ImageStudioTemplateUpdateOne) ClearSourceURL() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ImageStudioTemplateUpdateOne) SetSourceType(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableSourceType(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// ClearSourceType clears the value of the "source_type" field.
func (_u *ImageStudioTemplateUpdateOne) ClearSourceType() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearSourceType()
	return _u
}

// SetLicense sets the "license" field.
func (_u *ImageStudioTemplateUpdateOne) SetLicense(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableLicense(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// ClearLicense clears the value of the "license" field.
func (_u *ImageStudioTemplateUpdateOne) ClearLicense() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearLicense()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ImageStudioTemplateUpdateOne) SetAuthor(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableAuthor(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *ImageStudioTemplateUpdateOne) ClearAuthor() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *ImageStudioTemplateUpdateOne) SetMeta(v string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// SetNillableMeta sets the "meta" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableMeta(v *string) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetMeta(*v)
	}
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *ImageStudioTemplateUpdateOne) ClearMeta() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// SetTags sets the "tags" field.
func (_u *ImageStudioTemplateUpdateOne) SetTags(v []string) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ImageStudioTemplateUpdateOne) AppendTags(v []string) *ImageStudioTemplateUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ImageStudioTemplateUpdateOne) ClearTags() *ImageStudioTemplateUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetRequiresReference sets the "requires_reference" field.
func (_u *ImageStudioTemplateUpdateOne) SetRequiresReference(v bool) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetRequiresReference(v)
	return _u
}

// SetNillableRequiresReference sets the "requires_reference" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableRequiresReference(v *bool) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetRequiresReference(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImageStudioTemplateUpdateOne) SetEnabled(v bool) *ImageStudioTemplateUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableEnabled(v *bool) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ImageStudioTemplateUpdateOne) SetSortOrder(v int) *ImageStudioTemplateUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ImageStudioTemplateUpdateOne) SetNillableSortOrder(v *int) *ImageStudioTemplateUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ImageStudioTemplateUpdateOne) AddSortOrder(v int) *ImageStudioTemplateUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// Mutation returns the ImageStudioTemplateMutation object of the builder.
func (_u *ImageStudioTemplateUpdateOne) Mutation() *ImageStudioTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageStudioTemplateUpdate builder.
func (_u *ImageStudioTemplateUpdateOne) Where(ps ...predicate.ImageStudioTemplate) *ImageStudioTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageStudioTemplateUpdateOne) Select(field string, fields ...string) *ImageStudioTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageStudioTemplate entity.
func (_u *ImageStudioTemplateUpdateOne) Save(ctx context.Context) (*ImageStudioTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageStudioTemplateUpdateOne) SaveX(ctx context.Context) *ImageStudioTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageStudioTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageStudioTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageStudioTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagestudiotemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageStudioTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := imagestudiotemplate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := imagestudiotemplate.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := imagestudiotemplate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagestudiotemplate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Image(); ok {
		if err := imagestudiotemplate.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalImageURL(); ok {
		if err := imagestudiotemplate.OriginalImageURLValidator(v); err != nil {
			return &ValidationError{Name: "original_image_url", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.original_image_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageHash(); ok {
		if err := imagestudiotemplate.ImageHashValidator(v); err != nil {
			return &ValidationError{Name: "image_hash", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageDownloadError(); ok {
		if err := imagestudiotemplate.ImageDownloadErrorValidator(v); err != nil {
			return &ValidationError{Name: "image_download_error", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.image_download_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := imagestudiotemplate.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := imagestudiotemplate.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceName(); ok {
		if err := imagestudiotemplate.SourceNameValidator(v); err != nil {
			return &ValidationError{Name: "source_name", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceURL(); ok {
		if err := imagestudiotemplate.SourceURLValidator(v); err != nil {
			return &ValidationError{Name: "source_url", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := imagestudiotemplate.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.License(); ok {
		if err := imagestudiotemplate.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.license": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := imagestudiotemplate.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Meta(); ok {
		if err := imagestudiotemplate.MetaValidator(v); err != nil {
			return &ValidationError{Name: "meta", err: fmt.Errorf(`ent: validator failed for field "ImageStudioTemplate.meta": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageStudioTemplateUpdateOne) sqlSave(ctx context.Context) (_node *ImageStudioTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagestudiotemplate.Table, imagestudiotemplate.Columns, sqlgraph.NewFieldSpec(imagestudiotemplate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageStudioTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagestudiotemplate.FieldID)
		for _, f := range fields {
			if !imagestudiotemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagestudiotemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagestudiotemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(imagestudiotemplate.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(imagestudiotemplate.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imagestudiotemplate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagestudiotemplate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(imagestudiotemplate.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalImageURL(); ok {
		_spec.SetField(imagestudiotemplate.FieldOriginalImageURL, field.TypeString, value)
	}
	if _u.mutation.OriginalImageURLCleared() {
		_spec.ClearField(imagestudiotemplate.FieldOriginalImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.ImageHash(); ok {
		_spec.SetField(imagestudiotemplate.FieldImageHash, field.TypeString, value)
	}
	if _u.mutation.ImageHashCleared() {
		_spec.ClearField(imagestudiotemplate.FieldImageHash, field.TypeString)
	}
	if value, ok := _u.mutation.ImageDownloadError(); ok {
		_spec.SetField(imagestudiotemplate.FieldImageDownloadError, field.TypeString, value)
	}
	if _u.mutation.ImageDownloadErrorCleared() {
		_spec.ClearField(imagestudiotemplate.FieldImageDownloadError, field.TypeString)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(imagestudiotemplate.FieldPromptHash, field.TypeString, value)
	}
	if _u.mutation.PromptHashCleared() {
		_spec.ClearField(imagestudiotemplate.FieldPromptHash, field.TypeString)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagestudiotemplate.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(imagestudiotemplate.FieldSourceType, field.TypeString, value)
	}
	if _u.mutation.SourceTypeCleared() {
		_spec.ClearField(imagestudiotemplate.FieldSourceType, field.TypeString)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(imagestudiotemplate.FieldLicense, field.TypeString, value)
	}
	if _u.mutation.LicenseCleared() {
		_spec.ClearField(imagestudiotemplate.FieldLicense, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(imagestudiotemplate.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(imagestudiotemplate.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(imagestudiotemplate.FieldMeta, field.TypeString, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(imagestudiotemplate.FieldMeta, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(imagestudiotemplate.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, imagestudiotemplate.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(imagestudiotemplate.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequiresReference(); ok {
		_spec.SetField(imagestudiotemplate.FieldRequiresReference, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(imagestudiotemplate.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(imagestudiotemplate.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(imagestudiotemplate.FieldSortOrder, field.TypeInt, value)
	}
	_node = &ImageStudioTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagestudiotemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
