// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagestudiotemplate"
)

// ImageStudioTemplate is the model entity for the ImageStudioTemplate schema.
type ImageStudioTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// generation or edit
	Mode string `json:"mode,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// preview image URL or local public path
	Image string `json:"image,omitempty"`
	// remote preview image URL before local caching
	OriginalImageURL string `json:"original_image_url,omitempty"`
	// sha256 hash of the locally cached preview image
	ImageHash string `json:"image_hash,omitempty"`
	// last preview image download error
	ImageDownloadError string `json:"image_download_error,omitempty"`
	// sha256 hash of normalized prompt for import de-duplication
	PromptHash string `json:"prompt_hash,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// SourceName holds the value of the "source_name" field.
	SourceName string `json:"source_name,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// License holds the value of the "license" field.
	License string `json:"license,omitempty"`
	// Author holds the value of the "author" field.
	Author string `json:"author,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta string `json:"meta,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// RequiresReference holds the value of the "requires_reference" field.
	RequiresReference bool `json:"requires_reference,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder    int `json:"sort_order,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageStudioTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagestudiotemplate.FieldTags:
			values[i] = new([]byte)
		case imagestudiotemplate.FieldRequiresReference, imagestudiotemplate.FieldEnabled:
			values[i] = new(sql.NullBool)
		case imagestudiotemplate.FieldID, imagestudiotemplate.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case imagestudiotemplate.FieldKey, imagestudiotemplate.FieldMode, imagestudiotemplate.FieldTitle, imagestudiotemplate.FieldModel, imagestudiotemplate.FieldImage, imagestudiotemplate.FieldOriginalImageURL, imagestudiotemplate.FieldImageHash, imagestudiotemplate.FieldImageDownloadError, imagestudiotemplate.FieldPromptHash, imagestudiotemplate.FieldPrompt, imagestudiotemplate.FieldSourceName, imagestudiotemplate.FieldSourceURL, imagestudiotemplate.FieldSourceType, imagestudiotemplate.FieldLicense, imagestudiotemplate.FieldAuthor, imagestudiotemplate.FieldMeta:
			values[i] = new(sql.NullString)
		case imagestudiotemplate.FieldCreatedAt, imagestudiotemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageStudioTemplate fields.
func (_m *ImageStudioTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagestudiotemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagestudiotemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagestudiotemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagestudiotemplate.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case imagestudiotemplate.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case imagestudiotemplate.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case imagestudiotemplate.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imagestudiotemplate.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case imagestudiotemplate.FieldOriginalImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_image_url", values[i])
			} else if value.Valid {
				_m.OriginalImageURL = value.String
			}
		case imagestudiotemplate.FieldImageHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_hash", values[i])
			} else if value.Valid {
				_m.ImageHash = value.String
			}
		case imagestudiotemplate.FieldImageDownloadError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_download_error", values[i])
			} else if value.Valid {
				_m.ImageDownloadError = value.String
			}
		case imagestudiotemplate.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = value.String
			}
		case imagestudiotemplate.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case imagestudiotemplate.FieldSourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_name", values[i])
			} else if value.Valid {
				_m.SourceName = value.String
			}
		case imagestudiotemplate.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case imagestudiotemplate.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case imagestudiotemplate.FieldLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license", values[i])
			} else if value.Valid {
				_m.License = value.String
			}
		case imagestudiotemplate.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = value.String
			}
		case imagestudiotemplate.FieldMeta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value.Valid {
				_m.Meta = value.String
			}
		case imagestudiotemplate.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case imagestudiotemplate.FieldRequiresReference:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_reference", values[i])
			} else if value.Valid {
				_m.RequiresReference = value.Bool
			}
		case imagestudiotemplate.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case imagestudiotemplate.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageStudioTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *ImageStudioTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImageStudioTemplate.
// Note that you need to call ImageStudioTemplate.Unwrap() before calling this method if this ImageStudioTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageStudioTemplate) Update() *ImageStudioTemplateUpdateOne {
	return NewImageStudioTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageStudioTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageStudioTemplate) Unwrap() *ImageStudioTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageStudioTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageStudioTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("ImageStudioTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("original_image_url=")
	builder.WriteString(_m.OriginalImageURL)
	builder.WriteString(", ")
	builder.WriteString("image_hash=")
	builder.WriteString(_m.ImageHash)
	builder.WriteString(", ")
	builder.WriteString("image_download_error=")
	builder.WriteString(_m.ImageDownloadError)
	builder.WriteString(", ")
	builder.WriteString("prompt_hash=")
	builder.WriteString(_m.PromptHash)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("source_name=")
	builder.WriteString(_m.SourceName)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("license=")
	builder.WriteString(_m.License)
	builder.WriteString(", ")
	builder.WriteString("author=")
	builder.WriteString(_m.Author)
	builder.WriteString(", ")
	builder.WriteString("meta=")
	builder.WriteString(_m.Meta)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("requires_reference=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresReference))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// ImageStudioTemplates is a parsable slice of ImageStudioTemplate.
type ImageStudioTemplates []*ImageStudioTemplate
