// Code generated by ent, DO NOT EDIT.

package benefitcampaign

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the benefitcampaign type in the database.
	Label = "benefit_campaign"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldVisible holds the string denoting the visible field in the database.
	FieldVisible = "visible"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldThresholdAmount holds the string denoting the threshold_amount field in the database.
	FieldThresholdAmount = "threshold_amount"
	// FieldGrantAmount holds the string denoting the grant_amount field in the database.
	FieldGrantAmount = "grant_amount"
	// FieldRechargeScope holds the string denoting the recharge_scope field in the database.
	FieldRechargeScope = "recharge_scope"
	// FieldCopy holds the string denoting the copy field in the database.
	FieldCopy = "copy"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// EdgeClaims holds the string denoting the claims edge name in mutations.
	EdgeClaims = "claims"
	// Table holds the table name of the benefitcampaign in the database.
	Table = "benefit_campaigns"
	// ClaimsTable is the table that holds the claims relation/edge.
	ClaimsTable = "benefit_claims"
	// ClaimsInverseTable is the table name for the BenefitClaim entity.
	// It exists in this package in order to avoid circular dependency with the "benefitclaim" package.
	ClaimsInverseTable = "benefit_claims"
	// ClaimsColumn is the table column denoting the claims relation/edge.
	ClaimsColumn = "campaign_id"
)

// Columns holds all SQL columns for benefitcampaign fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldEnabled,
	FieldVisible,
	FieldStartsAt,
	FieldEndsAt,
	FieldThresholdAmount,
	FieldGrantAmount,
	FieldRechargeScope,
	FieldCopy,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultVisible holds the default value on creation for the "visible" field.
	DefaultVisible bool
	// DefaultRechargeScope holds the default value on creation for the "recharge_scope" field.
	DefaultRechargeScope string
	// RechargeScopeValidator is a validator for the "recharge_scope" field. It is called by the builders before save.
	RechargeScopeValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the BenefitCampaign queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByVisible orders the results by the visible field.
func ByVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisible, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByThresholdAmount orders the results by the threshold_amount field.
func ByThresholdAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThresholdAmount, opts...).ToFunc()
}

// ByGrantAmount orders the results by the grant_amount field.
func ByGrantAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantAmount, opts...).ToFunc()
}

// ByRechargeScope orders the results by the recharge_scope field.
func ByRechargeScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeScope, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByClaimsCount orders the results by claims count.
func ByClaimsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClaimsStep(), opts...)
	}
}

// ByClaims orders the results by claims terms.
func ByClaims(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClaimsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClaimsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClaimsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClaimsTable, ClaimsColumn),
	)
}
