// Code generated by ent, DO NOT EDIT.

package benefitcampaign

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldEnabled, v))
}

// Visible applies equality check predicate on the "visible" field. It's identical to VisibleEQ.
func Visible(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldVisible, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldEndsAt, v))
}

// ThresholdAmount applies equality check predicate on the "threshold_amount" field. It's identical to ThresholdAmountEQ.
func ThresholdAmount(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldThresholdAmount, v))
}

// GrantAmount applies equality check predicate on the "grant_amount" field. It's identical to GrantAmountEQ.
func GrantAmount(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldGrantAmount, v))
}

// RechargeScope applies equality check predicate on the "recharge_scope" field. It's identical to RechargeScopeEQ.
func RechargeScope(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldRechargeScope, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldEnabled, v))
}

// VisibleEQ applies the EQ predicate on the "visible" field.
func VisibleEQ(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldVisible, v))
}

// VisibleNEQ applies the NEQ predicate on the "visible" field.
func VisibleNEQ(v bool) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldVisible, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldEndsAt, v))
}

// ThresholdAmountEQ applies the EQ predicate on the "threshold_amount" field.
func ThresholdAmountEQ(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldThresholdAmount, v))
}

// ThresholdAmountNEQ applies the NEQ predicate on the "threshold_amount" field.
func ThresholdAmountNEQ(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldThresholdAmount, v))
}

// ThresholdAmountIn applies the In predicate on the "threshold_amount" field.
func ThresholdAmountIn(vs ...float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldThresholdAmount, vs...))
}

// ThresholdAmountNotIn applies the NotIn predicate on the "threshold_amount" field.
func ThresholdAmountNotIn(vs ...float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldThresholdAmount, vs...))
}

// ThresholdAmountGT applies the GT predicate on the "threshold_amount" field.
func ThresholdAmountGT(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldThresholdAmount, v))
}

// ThresholdAmountGTE applies the GTE predicate on the "threshold_amount" field.
func ThresholdAmountGTE(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldThresholdAmount, v))
}

// ThresholdAmountLT applies the LT predicate on the "threshold_amount" field.
func ThresholdAmountLT(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldThresholdAmount, v))
}

// ThresholdAmountLTE applies the LTE predicate on the "threshold_amount" field.
func ThresholdAmountLTE(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldThresholdAmount, v))
}

// GrantAmountEQ applies the EQ predicate on the "grant_amount" field.
func GrantAmountEQ(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldGrantAmount, v))
}

// GrantAmountNEQ applies the NEQ predicate on the "grant_amount" field.
func GrantAmountNEQ(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldGrantAmount, v))
}

// GrantAmountIn applies the In predicate on the "grant_amount" field.
func GrantAmountIn(vs ...float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldGrantAmount, vs...))
}

// GrantAmountNotIn applies the NotIn predicate on the "grant_amount" field.
func GrantAmountNotIn(vs ...float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldGrantAmount, vs...))
}

// GrantAmountGT applies the GT predicate on the "grant_amount" field.
func GrantAmountGT(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldGrantAmount, v))
}

// GrantAmountGTE applies the GTE predicate on the "grant_amount" field.
func GrantAmountGTE(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldGrantAmount, v))
}

// GrantAmountLT applies the LT predicate on the "grant_amount" field.
func GrantAmountLT(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldGrantAmount, v))
}

// GrantAmountLTE applies the LTE predicate on the "grant_amount" field.
func GrantAmountLTE(v float64) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldGrantAmount, v))
}

// RechargeScopeEQ applies the EQ predicate on the "recharge_scope" field.
func RechargeScopeEQ(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldRechargeScope, v))
}

// RechargeScopeNEQ applies the NEQ predicate on the "recharge_scope" field.
func RechargeScopeNEQ(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldRechargeScope, v))
}

// RechargeScopeIn applies the In predicate on the "recharge_scope" field.
func RechargeScopeIn(vs ...string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldRechargeScope, vs...))
}

// RechargeScopeNotIn applies the NotIn predicate on the "recharge_scope" field.
func RechargeScopeNotIn(vs ...string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldRechargeScope, vs...))
}

// RechargeScopeGT applies the GT predicate on the "recharge_scope" field.
func RechargeScopeGT(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldRechargeScope, v))
}

// RechargeScopeGTE applies the GTE predicate on the "recharge_scope" field.
func RechargeScopeGTE(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldRechargeScope, v))
}

// RechargeScopeLT applies the LT predicate on the "recharge_scope" field.
func RechargeScopeLT(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldRechargeScope, v))
}

// RechargeScopeLTE applies the LTE predicate on the "recharge_scope" field.
func RechargeScopeLTE(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldRechargeScope, v))
}

// RechargeScopeContains applies the Contains predicate on the "recharge_scope" field.
func RechargeScopeContains(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldContains(FieldRechargeScope, v))
}

// RechargeScopeHasPrefix applies the HasPrefix predicate on the "recharge_scope" field.
func RechargeScopeHasPrefix(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldHasPrefix(FieldRechargeScope, v))
}

// RechargeScopeHasSuffix applies the HasSuffix predicate on the "recharge_scope" field.
func RechargeScopeHasSuffix(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldHasSuffix(FieldRechargeScope, v))
}

// RechargeScopeEqualFold applies the EqualFold predicate on the "recharge_scope" field.
func RechargeScopeEqualFold(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEqualFold(FieldRechargeScope, v))
}

// RechargeScopeContainsFold applies the ContainsFold predicate on the "recharge_scope" field.
func RechargeScopeContainsFold(v string) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldContainsFold(FieldRechargeScope, v))
}

// CopyIsNil applies the IsNil predicate on the "copy" field.
func CopyIsNil() predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIsNull(FieldCopy))
}

// CopyNotNil applies the NotNil predicate on the "copy" field.
func CopyNotNil() predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotNull(FieldCopy))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.FieldLTE(FieldSortOrder, v))
}

// HasClaims applies the HasEdge predicate on the "claims" edge.
func HasClaims() predicate.BenefitCampaign {
	return predicate.BenefitCampaign(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClaimsTable, ClaimsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClaimsWith applies the HasEdge predicate on the "claims" edge with a given conditions (other predicates).
func HasClaimsWith(preds ...predicate.BenefitClaim) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(func(s *sql.Selector) {
		step := newClaimsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BenefitCampaign) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BenefitCampaign) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BenefitCampaign) predicate.BenefitCampaign {
	return predicate.BenefitCampaign(sql.NotPredicates(p))
}
